### ISSUE TITLE
PID Tuning of Heated Bed

### ISSUE THREAD

**Issue by tobashadow** [andrivet/ADVi3pp#101]
In Octoprint you have the ability using a Plugin (https://github.com/tohara/OctoPrint-Pidtune) to auto tune the PID tuning for the Hotend and the Bed heater  but after installing the ADVi3++ V3 Beta 2 The ability to run said plugin on the hot bed results in a failure. 

On your firmware is the option to run PID tuning on the Hotend but not the Heated Bed, could this feature be added.

**Comment by andrivet** [comment]
Please provide some details. Just a title is not enough.

**Comment by tobashadow** [comment]
Im sorry I thought I was filling out the form correctly, I put the following in the above.

I lost this ability in Octoprint when I went to this firmware and have recently changed my hot bed.

But I will add to it that the Hotend Pid tuning is wonderful I just wish I could do the Heated bed also if I wanted to

**Comment by andrivet** [comment]
Please explain the Feature Request (by providing some references for example) and edit your first comment to remove what is not necessary. "I lost this ability..." explains nothing.

**Comment by tobashadow** [comment]
Edited I hope this is what you need

**Comment by dtrazzi** [comment]
I believe this is a feature in the original firmware, it would be nice to have.

**Comment by andrivet** [comment]
@dtrazzi "I believe". Why are you believing this? And about which firmware (Maker Select Plus, Cocoon, Wanhao i3 Plus, ...), which version? In my stock firmware (Monoprice, 2.18), there is no such feature. Moreover, in the source code of Monoprice 2.1, PIDTEMPBED is clearly **not** defined, so Bed PID is not enabled. "it would be nice": why? Are you sure bed PID will work with this hardware?

**Comment by dtrazzi** [comment]
I have a maker select plus, not sure what firmware revision. And I just
remember running a PID tune on the bed, and storing the values. But maybe I
was mistaken.

It would be nice because it should allow for more stable bed temperatures,
though they are pretty stable as-is.

Why would a bed PID not work on this board?

**Comment by andrivet** [comment]
@dtrazzi "Why would a bed PID not work on this board?". This is an extract of Marlin sources (Configuration.h):

```
// Bed Temperature Control
// Select PID or bang-bang with PIDTEMPBED. If bang-bang, BED_LIMIT_SWITCHING will enable hysteresis
//
// Uncomment this to enable PID on the bed. It uses the same frequency PWM as the extruder.
// If your PID_dT above is the default, and correct for your hardware/configuration, that means 7.689Hz,
// which is fine for driving a square wave into a resistive load and does not significantly impact you FET heating.
// This also works fine on a Fotek SSR-10DA Solid State Relay into a 250W heater.
// If your configuration is significantly different than this and you don't understand the issues involved, you probably
// shouldn't use bed PID until someone else verifies your hardware works.
// If this is enabled, find your own PID constants below.
//#define PIDTEMPBED
```

**Comment by dtrazzi** [comment]
Ah, okay then.

**Comment by tobashadow** [comment]
If you load up the stock MonoPrice firmware (not sure on the Wanhao version) and use the PID tuning application that comes with Octoprint (https://github.com/tohara/OctoPrint-Pidtune) PID tuning of the bed works. Loading up any version of your firmware and it reports a error.

The code it runs if you select Bed in the PID Tuning is this 

else if (self.selectedController() == 'Bed') {
        			self.sendCommand("M303 E-1 S" + self.target() + " C" + self.cycles());

Trying to run M303 E-1 S in terminal  with ADVI3app installed returns  PID Autotune failed! Bad extruder number
Recv: ok

**Comment by andrivet** [comment]
Thanks for the (precise) information

**Comment by andrivet** [comment]
It looks like this:


![pidtuning1](https://user-images.githubusercontent.com/981049/47964143-91466b80-e035-11e8-9ba8-92dee5a8bda0.png)

![pidsettings](https://user-images.githubusercontent.com/981049/47964144-95728900-e035-11e8-98b0-4727d4405bff.png)

**Comment by andrivet** [comment]
Also related to #39
