### ISSUE TITLE
[FR] Bring back Pause, Stop, Settings button when printing from usb

### ISSUE THREAD

**Issue by blazze11** [andrivet/ADVi3pp#106]
Thank you for submitting your feedback to the ADVi3++ project.
Please use one of the templates below to fill out this box.

------------------------------------------------------------
### Feature Request
Please bring back the buttons on the print screen when printing from usb / octoprint. I always liked to use them in case something went wrong with my print.

**Comment by andrivet** [comment]
Already implemented in Beta 3 and duplicates of #64
