### ISSUE TITLE
Live Z adjustment (Babystepping)

### ISSUE THREAD

**Issue by strongbow1** [andrivet/ADVi3pp#108]
Live Z-Adjustment would be Awesome to have when Printing with different Filaments. Prusa i3 MK2, MK2s and MK3 have this function. I believe if you use Marlin 1.1.8 under the configuration_adv.h tab “Babystepping” will activate this function.

https://youtu.be/LvllHCgAML8 is an example of the feature.

**Comment by andrivet** [comment]
Can you please provide some information about what you have in your mind? Like a link to a similar feature.

**Comment by strongbow1** [comment]
Prusa i3 MK2, MK2s and MK3 have this function. I believe if you use Marlin 1.1.8 under the configuration_adv.h tab “Babystepping” will activate this function. I have done this with one of my own builds but its not as complicated as with the Wanhao i3 plus

Mit Freundlichen Grüsse
With Best Regards
Sandro Strimer

**Comment by andrivet** [comment]
It looks like this:

![printsettings](https://user-images.githubusercontent.com/981049/47965578-3f0f4580-e049-11e8-9f14-7fc992259bd6.png)

**Comment by chschmit** [comment]
What does the icon on the right signify? It looks like a baby carriage. 

On July 4, 2018 9:11:08 AM PDT, Sebastien Andrivet <notifications@github.com> wrote:
>It may look like this:
>
>![printsettings](https://user-images.githubusercontent.com/981049/42287163-9ca8cf30-7fb5-11e8-8916-9faa10dd55eb.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrivet/ADVi3pp-Marlin/issues/108#issuecomment-402518910

-- 
Sent from my Android Google Pixel.

**Comment by andrivet** [comment]
@chschmit I let you guess. The answer is in the title of this issue

**Comment by andrivet** [comment]
Note to myself: Pressing "Z" on the Main screen during a print should display the babystepping adjustment screen (ie print settings). Maybe, pressing on temps should to.
