### ISSUE TITLE
Allow Temp Change during filament change

### ISSUE THREAD

**Issue by zjed42** [andrivet/ADVi3pp#115]
### Feature Request
Not sure if M600 allows this, but you can't currently change hot end temp during filament swap. If changing between filaments with different temp requirements, it would be nice if you could change the temp while hot end is parked.

**Comment by andrivet** [comment]
This is a very good idea but too late to implement for version 3.0. So will be implemented for the next version.

**Comment by andrivet** [comment]
Implemented in version 5.7.0
