### ISSUE TITLE
Support for Wanhao Duplicator i3 Plus Mark II

### ISSUE THREAD

**Issue by fujin** [andrivet/ADVi3pp#119]
Apologies if this is being tracked elsewhere, I had a quick search but couldn't find anything.

I recently purchased a Di3+ which ended up being a Mk. II when it arrived 😁.

I note in the manual:
> Currently, ADVi3++ is only compatible with the Wanhao Duplicator i3 Plus version 1 printer and its clones. Version 2 (aka Wanhao Duplicator i3 Plus Mark II) will be supported in a future release.

If there's something I can do to help this along, let me know, otherwise feel free to close if invalid/tracked elsewhere or similar! Excited to try out `ADVi3++`!

**Comment by churd83** [comment]
Hey fujin! Are you working on butterflight? I assume you are :) Anyways I am about to compile a version of this firmware for my Mark II and I'll let you know if it works. I have flashed a previous version and it took the flash and operated but didn't work with bed leveling so I edited His source to work with Inductive sensors and I'm about to test it. Hopefully the LCD firmware will work with it as I do not know what to do with that. We shall see. I'll report back

**Comment by churd83** [comment]
Nope didn't work correctly, LCD buttons didn't all work, but i could control the printer by gcode commands through octoprint somewhat. Back to the drawing board :(.
I told the dev that the source code for the Wanhao D9 had if/else statements for the D9 and the i3 MarkII but he said he wouldn't look at it. I don't know much about coding but can understand most of it. If you want to go look at it, it's on github

**Comment by andrivet** [comment]
@churd83 I said I will not look at it **for the moment** (i.e. not before final release of 3.0). And I said also I will need help to support Mark II.

**Comment by andrivet** [comment]
@churd83 When you are talking about D9 source code, you are referring to this: https://github.com/garychen99/D9 ?

**Comment by churd83** [comment]
@andrivet I'm not going to bicker about what you said because I appreciate your work even though I can't use your hard work. Yes that is the source I was talking about when I pointed it out to you on Facebook. I just wanted you to look at it to see if it would help you merge for the MarkII. Like I said I'm not a coder, nor pretend to be, just trying to help.

**Comment by churd83** [comment]
@andrivet I'm willing to be a tester for the MarkII. Also @fujin does coding so he might be able to help since he has the MarkII as well

**Comment by fujin** [comment]
@churd83 I work on Betaflight (ew, butterflight.. 🤢)

@andrivet that's understandable regarding not before 3.0. If there's something in particular I can help with regarding the Mark II support, I'm happy to do my best. I have some amount of familiarity with embedded sw/hw practices from my experience with flight controllers.

**Comment by andrivet** [comment]
I will probably add Mark II support at the same time than proximity sensor support (#52) for Mark I.

**Comment by andrivet** [comment]
I add here the pictures I have about the Mark II. Do not hesitate to add more (of the mainboard for example).

![32713874_1370515026382613_2817972100680122368_o](https://user-images.githubusercontent.com/981049/40302686-42306a6e-5cf0-11e8-8556-332f2dea4717.jpg)
![32857586_1370514899715959_3159423946332307456_o](https://user-images.githubusercontent.com/981049/40302687-42499b06-5cf0-11e8-8d67-b12bc327a22f.jpg)
![32864664_1370514709715978_8322239433743007744_n](https://user-images.githubusercontent.com/981049/40302688-4262a31c-5cf0-11e8-8f2e-226d90db5c98.jpg)
![32899190_1842017529153145_919792707004530688_o](https://user-images.githubusercontent.com/981049/40302689-427979e8-5cf0-11e8-86ee-4d3243376e92.jpg)
![32900270_1370514496382666_7569186148967251968_o](https://user-images.githubusercontent.com/981049/40302690-4292ad8c-5cf0-11e8-9131-a2a0bb40e5ec.jpg)
![32941418_1370547509712698_3196190962330107904_o](https://user-images.githubusercontent.com/981049/40302691-42aef654-5cf0-11e8-9305-b3e9216378ab.jpg)
![33067060_1370514199716029_1396405094697664512_o](https://user-images.githubusercontent.com/981049/40302692-42c6ce00-5cf0-11e8-8084-f76d610709b4.jpg)

**Comment by fujin** [comment]
I put these in the FB thread as well.

![33420250_950398208467440_9001717673880453120_n](https://user-images.githubusercontent.com/6873/40396942-f27b4aee-5e83-11e8-8ad4-77059c1f5e1e.jpg)
![33364909_950398241800770_8981309183290769408_n](https://user-images.githubusercontent.com/6873/40396943-f376c374-5e83-11e8-8916-9545b369ace8.jpg)
![33401574_950398291800765_3082892194667823104_n](https://user-images.githubusercontent.com/6873/40396946-f4676202-5e83-11e8-8290-0cd71f84053e.jpg)

Let me know if you need any other specific images. 💯

**Comment by domverity** [comment]
+1 for mkII support, happy to offer testing, photos etc if it would be useful...

**Comment by andrivet** [comment]
@all Do you receive a manual with the Mark II? If yes, can you post here the pages about bed leveling?

**Comment by domverity** [comment]
The physical manual I received with mine was ancient (doesn't even mention auto bed levelling), the new one is here https://drive.google.com/file/d/1-WZi-uHYdpV6g0gGUegqxxxRJ-6XwiMW/view?usp=sharing though don't get too excited, it's not the most detailed...

**Comment by fujin** [comment]
Confirming the manual did not have anything regarding auto bed levelling.

These links sent to me by Wanhao may be of assistance:
- https://www.dropbox.com/s/6xwsdjzv5ljfsg1/OQD08017.A.ABL-SENSOR%281%29.pdf?dl=0
- https://www.dropbox.com/s/pphdambavm4occf/OQD08021.doc%20Sensor%20replacement.pdf?dl=0
- https://www.youtube.com/watch?v=8U04vtcbisM&feature=youtu.be

**Comment by churd83** [comment]
@avdrivet what exactly are you needing to know from the manual for the ABL sensor. I might know what you need to know. Why not just make a list of what you need to know and I'm sure me and others can get you that info.

**Comment by andrivet** [comment]
@fujin I look at the video. The adjustment of the sensor is not easy.

**Comment by fujin** [comment]
@andrivet agreed. The good news is, once set, it seems to stay put. I also believe it may be possible to use [M851](https://reprap.org/wiki/G-code#M851:_Set_Z-Probe_Offset) with the stock Marlin 1.1.4 `M851 Z-XX.XX` for fine grain adjustment (e.g. +/- 0.01) although I've not tested as of yet. It defaults to `Z-0.20`

I ordered a BLTouch just in case this ends up being difficult.

**Comment by churd83** [comment]
@fujin yes you will need to use the m851 command to fine tune your z offset because everyone's sensor won't trigger at the same height, nor will everyone's sensor be mounted at the same height. @andrivet should State that in the write-up for this firmware/printer.

**Comment by deloosem** [comment]
@fujin I think after each autolevel it goes back to default. So you need to run 851 after every autolevel. 

(Hmm I am not sure anymore about what I said here. It seems it sticks but in any case run it)

**Comment by deloosem** [comment]
I can't wait for your support of the mark 2. As of now the wanhao i3 plus mark II autolevel does NOT work.
It even messes a perfect level up ... lol (but then again the supplied allen wrenches just snap in two by just looking at them :)  )

**Comment by deloosem** [comment]
![20180605_014447](https://user-images.githubusercontent.com/37427149/41005851-72b85a58-691f-11e8-8729-640e774d07c7.jpg)
![20180605_013755](https://user-images.githubusercontent.com/37427149/41005863-80bf41a2-691f-11e8-9965-c7178c128c4d.jpg)
![20180605_013923](https://user-images.githubusercontent.com/37427149/41005913-b2d5053c-691f-11e8-8f2b-86d6ccd233a0.jpg)
![20180605_013616](https://user-images.githubusercontent.com/37427149/41005914-b306b8e8-691f-11e8-93c4-d25bbd89f5bf.jpg)
![20180605_013644](https://user-images.githubusercontent.com/37427149/41005915-b335d024-691f-11e8-9b37-209ff447bb32.jpg)
![20180605_013630](https://user-images.githubusercontent.com/37427149/41005916-b35d0b26-691f-11e8-970d-91f32ee382db.jpg)
![20180605_013923](https://user-images.githubusercontent.com/37427149/41005917-b3942e80-691f-11e8-9200-65d39831f50e.jpg)
![20180605_013624](https://user-images.githubusercontent.com/37427149/41005918-b3c0cb48-691f-11e8-9e4b-4eb03abfb8e9.jpg)
![20180605_013755](https://user-images.githubusercontent.com/37427149/41005919-b3ef3172-691f-11e8-93ce-62c362e606ee.jpg)
![20180605_013637](https://user-images.githubusercontent.com/37427149/41005920-b422514c-691f-11e8-9bfc-bdb36363e876.jpg)
![20180605_013718](https://user-images.githubusercontent.com/37427149/41005921-b462ea22-691f-11e8-89ef-b0804a5460bb.jpg)

**Comment by benjamin-goldman** [comment]
has the auto level fail been fixed yet?

**Comment by andrivet** [comment]
@deloosem I will implement Mark II support only if supporters on Patreon votes for it (I see you will be able to vote since you are a supporter of the project).

@bgoldman69 "has the auto level fail been fixed yet?". I do not know what you are talking about. And for support, please use Facebook ADVi3++ page or Patreon. GitHub issues are reserved for technical things.

**Comment by deloosem** [comment]
Where do I vote?

**Comment by andrivet** [comment]
Votes are not yet open. See: https://www.patreon.com/posts/on-road-to-4-19201225

**Comment by Electomanic** [comment]
Found som images of the PCB online and made a comparison between the plus and plus mark ii.
Looks fairly similar.

I don't have the printer yet but have ordered it and hope to get hacking once it arrives.

![pcb wanhao i3 plus and plus mark ii](https://user-images.githubusercontent.com/24415771/45594155-27dfa000-b996-11e8-902a-60dca2f6bac1.jpg)

**EDIT:**

Images from:
https://www.3dprima.com/accessories/spare-parts/wanhao-i3-plus/wanhao-main-board-to-duplicator-i3-plus/a-22090/
https://www.3dprima.com/parts/spare-parts/wanhao/wanhao-main-board-to-duplicator-i3-plus-v5-4/a-22960/

**Edit 2:**

After looking at the other pictures in this thread my guess is the new unlabeled 3 pin connector is the z-probe and the the z-min connector has been moved to the hotend connector

**Comment by churd83** [comment]
If anyone on here is on the Wanhao Duplicator I3 facebook group, https://www.facebook.com/groups/i3plus/, I have ported Sebastian's hard work to work with the MarkII printer. There is a long write up on the Group if you are interested.

**Comment by churd83** [comment]
here are some more photos
![img_20190113_122527 1](https://user-images.githubusercontent.com/1325684/52185293-36671080-27ec-11e9-815f-8bfdf9042c65.jpg)
![img_20190113_122502 1](https://user-images.githubusercontent.com/1325684/52185311-58609300-27ec-11e9-930a-d4844c91b4e3.jpg)

**Comment by ringerc** [comment]
(This comment said I had a mkII - I was mistaken and it's a mkI with some minor improvements over the WanHao stock model.)

**Comment by ringerc** [comment]
@churd83 Would you mind adding a link to your port/fork here?

**Comment by andrivet** [comment]
@ringerc I have already merged the work of @churd83. His source code is in his github repository

**Comment by andrivet** [comment]
@ringerc The only think I need is tests and to know if you have modified your printer and how.

**Comment by ringerc** [comment]
@andrivet I was mistaken - it's a mk1 clone but the vendor has taken a selection of the more minor enhancements from the mk2: improved thumbwheels for bed leveling, improved power connection so there's no need for the MOSFET hack, etc.

No auto bed leveling, etc. Sorry for wasting your time.

**Comment by andrivet** [comment]
Supported in version 4.0 except the power loss recovery (https://github.com/andrivet/ADVi3pp-Marlin/issues/205)
