### ISSUE TITLE
[FR] Make manually moving smoother.

### ISSUE THREAD

**Issue by ewortzman** [andrivet/ADVi3pp#121]
Currently, when you go to manually move the nozzle, if you press and hold the button, it moves in a very jittery pattern, moving by the default step size (which I think is 1mm?), then stopping momentarily, then moving again the same step.  It would be nice if either the nozzle moved smoothly until the button is released, rather than jittering its way around, or if there were an option to change the default step size for manually moving, so that I can move it around significantly without rattling the entire table.

**Comment by andrivet** [comment]
Fix in version 3.0.0. Movement are now smother (and slower)
