### ISSUE TITLE
Ability to enter Touch Sensor (X, Y) offset position by LCD instead of hard coded 

### ISSUE THREAD

**Issue by Martin-Dolan** [andrivet/ADVi3pp#125]
Currently the (X, Y) position of the touch sensor probe in relation to the hotend nozzle is hardcoded. It would be great if it could be entered via the LCD instead of having to recompile the firmware.

Perhaps an option on the screen where you set up the sensor to enter  the offset of -15mm to +15 mm on the X and Y axis?

Or a screen where the nozzle moves to the middle of the bed and waits, (with the Z height at say 10mm). 
You mark on the bed under the nozzle with a sharpie.
You then use X, Y arrows to move the touch sensor over the sharpie mark and when correct press conform button.
The offset is calculated and stored in non volatile memory.

**Comment by lightseeker34** [comment]
I have designed a custom toolhead and am dealing with this exact problem right now. To be able to do this without editing code would be a real game changer.

**Comment by andrivet** [comment]
It may look like this:

![sensorsettings](https://user-images.githubusercontent.com/981049/44299035-89a4df80-a2ee-11e8-92aa-d2e938f6c4c7.png)

**Comment by andrivet** [comment]
Note to myself: In the User Manual, provide values (X, Y, Z) for my own supports but also for Teaching Tech ones (https://www.youtube.com/watch?v=BV11-VOQjMc). Or provide them on this screen like this:

![sensorsettings](https://user-images.githubusercontent.com/981049/44300645-d9919f80-a30a-11e8-989f-cded83bde5cf.png)

**Comment by andrivet** [comment]
Full implemented in Alpha 2
