### ISSUE TITLE
Bug: cannot set sensor/nozzle height lower than -2 mm 

### ISSUE THREAD

**Issue by ghost** [andrivet/ADVi3pp#132]
I tried to manually adjust the height oc the nozzle (with respect to the sensor).

The automatic method calculated -2.16mm. As soon as i tried to change that, it jumped to -2 and could not be set lower.

**Comment by andrivet** [comment]
I do this on purpose because I thought -2 was enough. I now see it is not the case.

**Comment by ghost** [comment]
That's what I thought. Is it possible to remove the limit completely?

**Comment by andrivet** [comment]
Not completely (for technical reasons). But I will set bigger boundaries. It will be in the next version (probably 3.0.2)

**Comment by andrivet** [comment]
Fixed in 3.0.2
