### ISSUE TITLE
M600 Button on printing screen

### ISSUE THREAD

**Issue by LotDev** [andrivet/ADVi3pp#139]
------------------------------------------------------------
### Feature Request

- [x] Your request is not specific to your setup but can benefit to many people 
- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [x] You have provided a short but meaningful title
- [x] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [x] You have provided objective **facts**, not your personal feelings, your personal preferences.

I am sure that more than just I can benefit from this feature if you decided to implement it, and we will be thankful if you do. I know you been implementing the M600 command in the printer and it is quite useful but the problem is that it can be only used when connected through a computer (octoprint) or in the gcode. I think it will be a great thing if you had a button the preformed the M600 command on the printing page. Thanks for the time and your support and for your work on this project!

Also the feature will provide the possibility to change your  filament  When you are about to run out and this allows you to do this without a computer.

**Comment by andrivet** [comment]
Can you please use the issue template?

**Comment by LotDev** [comment]
Sorry about that, fixed it and used the template you provided!

**Comment by andrivet** [comment]
It may look like this:

![print](https://user-images.githubusercontent.com/981049/42287263-fa441942-7fb5-11e8-812a-ed8b5cb2206d.png)

**Comment by LotDev** [comment]
Looks great! Thanks for your work man!

**Comment by noel2763** [comment]
Awesome. Thanks a lot. Will the LCD show Resume or Extrude more plastic button using M600 advance pause feature?

**Comment by andrivet** [comment]
Implemented in version 4.0
