### ISSUE TITLE
[FR ]Disable screen dimming of the LCD

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#14]
### Feature Request

From Johannes Schoeller:

Disable screen dimming of the LCD (yes/no).

**Comment by andrivet** [comment]
As a (some sort of) workaround, I have change the delay before dimming the screen.

**Comment by TTVert** [comment]
By "added the enhancements" does that mean this should be applied to  2.1.0?  Can someone possibly tell me how I can define the screen dim timeout?  I think it's maybe 60 seconds now?  I'd like to possibly make it a few hours.  It's very hard for me to see when dim.

Dave

**Comment by andrivet** [comment]
Dimming will be configurable (at a minimum on/off) in version 3

**Comment by andrivet** [comment]
Implemented in version 3.0.0

![096_lcd](https://user-images.githubusercontent.com/981049/36633884-d0a61b5a-199c-11e8-9d97-6b426dc5bacf.png)
