### ISSUE TITLE
Can't find source code for BLTouch version of firmware.

### ISSUE THREAD

**Issue by Ali-Niazi021** [andrivet/ADVi3pp#141]
Hey, so I'm using a BLTouch and recently rewired so it corresponds with the manual so I don't have to modify firmware anymore.

However, I'm using a different mount and therefore need to change the probe offset values in the configurations file.

All the sources I've found are of the version which doesn't have BLTouch enabled, where can I find the source code of the BLTouch release? The included source in the latest release doesn't have it enabled.

Also if it's easier, how do I enable BLTouch in the non-BLTouch source?

Thanks

**Comment by andrivet** [comment]
As stated in the template when you are creating an issue, please DO NOT use GitHub issues for support. For support, you have the Patreon page or the Facebook ADVi3++ page.
