### ISSUE TITLE
Support for filament width sensor and volumetric extrusion

### ISSUE THREAD

**Issue by ghost** [andrivet/ADVi3pp#143]
- [x] This issue is **NOT** about support. This is not the right place for support (there is an [ADVI3++ Facebook page](https://www.facebook.com/advi3pp/) for that)

------------------------------------------------------------
### Feature Request

- [x] Your request is not specific to your setup but can benefit to many people
- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [x] You have provided a short but meaningful title
- [x] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [x] You have provided objective **facts**, not your personal feelings, your personal preferences.

Detailed description of the feature request:

Integrating support for an optical filament width sensor like the one linked below would enable leveraging of Marlin's existing volumetric extrusion feature. This would allow the printer to dynamically change the extrusion multiplier in response to fluctuations in filament width. As a bonus, such a sensor could also be used to detect filament run-outs.

Some benefits would include:
- Greater extrusion accuracy
- Increased compatibility with homemade filaments or those with poor manufacturing tolerances
- Obviate the need to manually tune extrusion multipliers

Links:
Thingiverse project: https://www.thingiverse.com/thing:454584
Sensor: https://objectswithintelligence.weebly.com/store.html

**Comment by andrivet** [comment]
Next time, please the template otherwise I will close the issue.

**Comment by numerocasuale** [comment]
Is there also another version of the sensor? Like an honest price version for example? Or a non thief version? Asking for a friend.

**Comment by andrivet** [comment]
After studying your feature request, it looks like very specific to the projects you mentioned. And apparently, the sensor is no more available for purchase (I tried). So unless there is a viable alternative, I will not implement this feature.
