### ISSUE TITLE
Realtime display of bed leveling compensation during printing

### ISSUE THREAD

**Issue by jvanick** [andrivet/ADVi3pp#149]
It would be cool if we could have a realtime display of the bed leveling compensation during printing... not sure if it's feasible or not, or what the performance implications may be.

**Comment by andrivet** [comment]
Please follow the template when submitting a feature request. In particular, your issue does not respect the rule "You have provided objective **facts**, not your personal feelings, your personal preferences"

**Comment by andrivet** [comment]
Closing because this issue does not follow the rules
