### ISSUE TITLE
Enable S-Curve acceleration

### ISSUE THREAD

**Issue by brianhealey** [andrivet/ADVi3pp#152]
Thank you for submitting your feedback to the ADVi3++ project.

Please be sure to review the checklists below before submitting and use one of the templates. 

**It is mandatory**. If you do not comply with these rules, I will **delete** your issue.

- [x] This issue is **NOT** about support. This is not the right place for support (there is an [ADVI3++ Facebook page](https://www.facebook.com/advi3pp/) for that)

------------------------------------------------------------
### Feature Request

- [x] Your request is not specific to your setup but can benefit to many people
- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [x] You have provided a short but meaningful title
- [x] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [x] You have provided objective **facts**, not your personal feelings, your personal preferences.

Note: It is no more necessary to add "[FR]" in the title. You can, if you want, label your issue with "enhancement".

Detailed description of the feature request:

The bugfix 1.1.x branch of marlin contains a `#define S_CURVE_ACCELERATION` feature that is supposed to enable better jerk and acceleration handling.  I have compiled it into my own personal build but I would love to see it officially supported.

**Comment by andrivet** [comment]
Implemented in version 4.0
