### ISSUE TITLE
Graph as default view or GCode to show the graph view

### ISSUE THREAD

**Issue by FierceBun** [andrivet/ADVi3pp#153]
Many folx use remote systems to operate thier printer with minimal physical interaction.  The most useful screen from across the room is the activity graph.  Either an option to tick to make it the default screen, or a command that can be sent along with gcode to open the graph screen would facilitate this usage.

**Comment by andrivet** [comment]
This is very specific to the way you are using your printer. So I do not thing that option 1 is appropriate. Option 2 (by GCode) is something I already think about (not just for the Temp Graph). But please, please, please, use the form when submitting an issue.

**Comment by jmdefino** [comment]
I was going to suggest the same. The original firmware had a progress bar. This was very useful as you could see it from across the room instead of having to get right to the screen to view the percentage completed. Thanks for your consideration.

**Comment by LordJakson** [comment]
I thought about the same. With the command M24 (Start SD print) the display should swich to the Temp Graph so I can start it remoly.

**Comment by andrivet** [comment]
Implemented in version 5.5.0. Implicates major refactoring of code.
