### ISSUE TITLE
[FR] Please support the Wanhao i3 plus MARK II

### ISSUE THREAD

**Issue by deloosem** [andrivet/ADVi3pp#154]
Thank you for submitting your feedback to the ADVi3++ project.

Please be sure to review the checklists below before submitting and use one of the templates. 

**It is mandatory**. If you do not comply with these rules, I will **delete** your issue.

- [ ] This issue is **NOT** about support. This is not the right place for support (there is an [ADVI3++ Facebook page](https://www.facebook.com/advi3pp/) for that)

------------------------------------------------------------
### Feature Request

- [ ] Your request is not specific to your setup but can benefit to many people
- [ ] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [ ] You have provided a short but meaningful title
- [ ] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [ ] You have provided objective **facts**, not your personal feelings, your personal preferences.

Note: It is no more necessary to add "[FR]" in the title. You can, if you want, label your issue with "enhancement".

Detailed description of the feature request:

_Please provide information (such as links to web sites, blogs, technical description)._

------------------------------------------------------------
### Bug Report

- [ ] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [ ] You have tested with the **latest** version of ADVi3++ (including Beta releases)
- [ ] You are able to reproduce the bug
- [ ] You are able to describe step by step the process to reproduce the bug

* Exact model of your **printer**:
* **ADVi3++** exact version:
* Printing using **SD card** or **USB**:
* **For USB printing only** Software used to print with its exact version:

#### Description of the bug

* Expected behaviour:
* Actual behaviour:
* Steps to reproduce:
  - Do this
  - Do that

**Comment by andrivet** [comment]
You really think that creating a duplicate (#119), not following the form and putting "please" in the title will convince me to support your printer?
