### ISSUE TITLE
Filament load/unload artifacts

### ISSUE THREAD

**Issue by chschmit** [andrivet/ADVi3pp#156]
### Bug Report
Wanhao i3 Duplicator Plus
ADVi3 3.0.2
print from SD card

#### Description of the bug
Expected behaviour: loading/unloading comments shown in the middle of the screen.
Actual behaviour: loading/unloading comments are shown but includes the previously printed filename 
after the comments which messes up the comment text...word wrapping issue.

* Steps to reproduce:
This only happens after something was printed and then choose to load/unload filament. If the printer is restarted, the issue isn't there.

**Comment by DynaMight1124** [comment]
I can confirm this happens to me also. Latest version (BLTouch)

**Comment by DynaMight1124** [comment]
![2018-07-21 10 52 03](https://user-images.githubusercontent.com/18290628/43040206-cf120f44-8d35-11e8-9bd2-ca221657bc8a.jpg)

Heres a picture of the issue

**Comment by andrivet** [comment]
Fixed in version 4.0
