### ISSUE TITLE
3.0.2 LCD update still shows 3.0.1?

### ISSUE THREAD

**Issue by riaqn** [andrivet/ADVi3pp#157]
### Bug Report
* Monoprice Maker Select Plus
* 3.0.2, both mainboard and LCD

#### Description of the bug
- Used to 3.0.1, both mainboard and LCD
- flash 3.0.2 LCD
- flash 3.0.2 mainboard
- use the firmware to show the version, shows 3.0.1 LCD, 3.0.2 mainboard.
- flash 3.0.2 LCD many times again
- no change.

Hopefully this is just because 3.0.1 and 3.0.2 share same LCD images. Or because the author forgot to update the only version number.

**Comment by kickhad** [comment]
Experiening the same on my Wanhao i3 Plus. 

The LCD flash cycles through all the images

**Comment by andrivet** [comment]
Duplicate of #148. Please do not create duplicates
