### ISSUE TITLE
ADVi3 User Manual 3.0.2 - GCode Extrude 

### ISSUE THREAD

**Issue by Deose** [andrivet/ADVi3pp#161]
-----------------------------------------------------------
### Bug Report

- [Y] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [Y] You have tested with the **latest** version of ADVi3++ (including Beta releases)
- [Y] You are able to reproduce the bug
- [Y] You are able to describe step by step the process to reproduce the bug

* Exact model of your **printer**: N/A - Monoprice Maker Select Plus
* **ADVi3++** exact version: N/A - ADVi3pp-BLTouch-Mainboard-3.0.2.hex
* Printing using **SD card** or **USB**: N/A - Both
* **For USB printing only** Software used to print with its exact version: N/A - Ultimaker Cura 3.4.1

#### Description of the bug

* Expected behaviour: 3mm of filament should be extruded.
* Actual behaviour: 30mm of filament is extruded.
* Steps to reproduce:
  - enter G1 F140 E30 as a line in Starting Gcode.
  - Print something.
------------------

So I think this is just a typo in the manual basically. the line "G1 F140 E30" prints 3cm, not 3mm (page 82 of ADVi3.User.Manual.3.0.2.pdf)

**Comment by andrivet** [comment]
Fixed (online and in PDF)
