### ISSUE TITLE
Title of last print stuck on LCD screen

### ISSUE THREAD

**Issue by Deose** [andrivet/ADVi3pp#163]
### Bug Report

- [Y] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [Y] You have tested with the **latest** version of ADVi3++ (including Beta releases)
- [Y] You are able to reproduce the bug
- [Y] You are able to describe step by step the process to reproduce the bug

* Exact model of your **printer**:
* **ADVi3++** exact version: ADVi3pp-BLTouch-Mainboard-3.0.2.hex
* Printing using **SD card** or **USB**: SD

#### Description of the bug

* Expected behaviour: Text on screen shouldn't have file name outside of printing that file or file selection
* Actual behaviour: At the end of different lines describing which action is happening, the name of the last file printed is added.
* Steps to reproduce:
  - Print something via SD card. 
  - Stop the print before it finishes.
  - Do something else (e.g. BLTouch Leveling, loading filament, etc.)
![photo_2018-08-05_11-47-49](https://user-images.githubusercontent.com/39196348/43688851-8f4db7b6-98a5-11e8-8b5d-179d53addc96.jpg)
![photo_2018-08-05_11-47-59](https://user-images.githubusercontent.com/39196348/43688852-9353a604-98a5-11e8-9a79-f4e56641ddf3.jpg)

**Comment by chschmit** [comment]
I'd identified this in Issue #156

On August 5, 2018 11:49:18 AM PDT, Deose <notifications@github.com> wrote:
>### Bug Report
>
>- [Y] You have checked that you are not creating a **duplicate** of an
>existing (maybe closed) issue (use the search)
>- [Y] You have tested with the **latest** version of ADVi3++ (including
>Beta releases)
>- [Y] You are able to reproduce the bug
>- [Y] You are able to describe step by step the process to reproduce
>the bug
>
>* Exact model of your **printer**:
>* **ADVi3++** exact version: ADVi3pp-BLTouch-Mainboard-3.0.2.hex
>* Printing using **SD card** or **USB**: SD
>
>#### Description of the bug
>
>* Expected behaviour: Text on screen shouldn't have file name outside
>of printing that file or file selection
>* Actual behaviour: At the end of different lines describing which
>action is happening, the name of the last file printed is added.
>* Steps to reproduce:
>  - Print something via SD card. 
>  - Stop the print before it finishes.
>  - Do something else (e.g. BLTouch Leveling, loading filament, etc.)
>![photo_2018-08-05_11-47-49](https://user-images.githubusercontent.com/39196348/43688851-8f4db7b6-98a5-11e8-8b5d-179d53addc96.jpg)
>![photo_2018-08-05_11-47-59](https://user-images.githubusercontent.com/39196348/43688852-9353a604-98a5-11e8-9a79-f4e56641ddf3.jpg)
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrivet/ADVi3pp-Marlin/issues/163

-- 
Sent from my Android Google Pixel.

**Comment by andrivet** [comment]
@chschmit Yes, but this issue is more general. This is why I have not marked it as duplicate.

**Comment by andrivet** [comment]
Fixed in version 4.0
