### ISSUE TITLE
Blobs in corners of the prints

### ISSUE THREAD

**Issue by runam0K** [andrivet/ADVi3pp#167]
### Bug Report

* Exact model of your **printer**: Wanhao i3 Plus
* **ADVi3++** exact version: 3.0.2
* Printing using **SD card** or **USB**: USB
* **For USB printing only** Software used to print with its exact version: Octoprint 1.3.9

#### Description of the bug

Since the upgrade to ADVi3++ I have the problem that the printed objects have blobs at the corners. The edges are not straight. I have attached some pictures.

I'm not the only one with this problem either. My friend has exactly the same problems since switching to ADVi3++.
He tried all settings in the slicer several times. e.g. retraction, coasting distance.

The slicer is Simplify3D in both cases.

How can the problem be solved? Why did the problem not happen with the default firmware?

![img_7733](https://user-images.githubusercontent.com/3284319/45360274-5a248280-b5cf-11e8-93fb-3b10502f5787.JPG)
![img_7734](https://user-images.githubusercontent.com/3284319/45360275-5abd1900-b5cf-11e8-9eab-26a95b61c803.JPG)
![img_7735](https://user-images.githubusercontent.com/3284319/45360276-5abd1900-b5cf-11e8-9445-262ffefa167c.JPG)
![img_7729](https://user-images.githubusercontent.com/3284319/45360278-5abd1900-b5cf-11e8-8648-8ca044f3af52.JPG)
![img_7730](https://user-images.githubusercontent.com/3284319/45360279-5abd1900-b5cf-11e8-90ec-722108bfb97d.JPG)
![img_7731](https://user-images.githubusercontent.com/3284319/45360280-5b55af80-b5cf-11e8-877a-8e426ef1efef.JPG)
![img_7732](https://user-images.githubusercontent.com/3284319/45360282-5b55af80-b5cf-11e8-8803-ef7c2162aff4.JPG)

**Comment by andrivet** [comment]
Please do not abuse GitHub issues with support requests. This is not the right place.

**Comment by runam0K** [comment]
So where is the right place for problems with this firmware if not here?

**Comment by andrivet** [comment]
In the template of issues, it is clearly stated: "This issue is **NOT** about support". You may get support from the community on the Facebook page, and from myself on Patreon.
