### ISSUE TITLE
LCD Touch panel support

### ISSUE THREAD

**Issue by ModMike** [andrivet/ADVi3pp#174]
I have a Creatbot DX that uses the same touch panel as the Wanhao. Can I port the settings to Marlin 2.0.x?

Thank you.

**Comment by churd83** [comment]
Marlin 2.0.x is for 32bit only from my understanding

**Comment by ModMike** [comment]
It works on both 32 and 8 bit.  I have it running on 2 different 8 bit board and 3 32bit boards.

**Comment by andrivet** [comment]
I do not plan to support Creatbox printers

**Comment by ModMike** [comment]
I didn’t ask you to support Creatbot, I asked you if you if you could support the Dwin touch panel from the Wanhao printer.

How do I configure it so Marlin sees it?  I get that it’s. a serial device acting as a host.  Are you really unwilling to share that knowledge and help the community at large appreciate your work?

**Comment by andrivet** [comment]
@ModMike Do I owe you something? Are you assuming that I have an infinite amount of time to explain everything? I already share a lot (for example: http://sebastien.andrivet.com/en/posts/wanhao-duplicator-i3-plus-3d-printer/)

**Comment by ModMike** [comment]
Vraiment?  Très chic comme réponse.

**Comment by andrivet** [comment]
Closing, delete comments because the question was not related to this project.
