### ISSUE TITLE
Version 4.0.0 Alpha 3 know issues

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#186]
This issue is an inventory of all known issues of version 4.0.0 Alpha 3. Checked items are fixed in Alpha 4.

* [x] Diagnosis screen is implemented with the state of pins (digital and analog when applicable)
* [x] When a PID tuning is finished, if you press back, you are back to the Temperature Graph page, not the PID tuning page. 
* [x] When a PID tuning is finished, the temperature displayed is the default one, not the chosen one. In fact, none of the values were correctly set. Add also some messages during PID.
* [ ] Sometimes when hitting Pause, the head goes in the corner as expected but then suddenly goes over the piece being printed.
* [ ] (Sometimes) when pressing Back in the Load/Unload screen, the E stepper motor does not stop
* [x] When printing from SD, the percentage stays at 0%. There were plenty of other bugs in this area.
* [ ] Make binaries for Balco Touch UK (stop pin = 6)
* [x] Change multipliers (Z-height, Babysteps) to more granular values
* [x] On the main screen, the top left corner goes now directly to Print Settings if there is a print running. Otherwise, it shows temperatures

**Comment by contraspec** [comment]
Wanhao i3 plus mk2 - Alpha3 
Flashed firmware today, ran a test print, see below for my findings.

* no pause / resume function on print screen, required for the power resume.
* z height offset adjusted as close as possible to 0.1mm as per printer settings.
* auto bed level only measures 70% of  bed , alpha2 used whole surface.
* after leveling, started print, nozel not compressing the first layer into bed, very loose layer.
* after aprox 35min into print the x-axis went stupid,  x would not home correct. Had to turn printer off to reset, printer behaved ok after reboot.
* started a reprint and abot 30min into print it did it again, print position was not on same height, so i cant say its a gcode error. See attached video. 
So i do think it is a possible bug. Print from sdcard, gcode from S3D

[VID-20190103-WA0001.zip](https://github.com/andrivet/ADVi3pp-Marlin/files/2724895/VID-20190103-WA0001.zip)

**Comment by andrivet** [comment]
@contraspec 
* "z height offset adjusted as close as possible to 0.1mm as per printer settings". Can you elaborate a little? I do not understand. Have you used the z offset tuning?
* "auto bed level only measures 70% of bed , alpha2 used whole surface". Have you set the right sensor in the sensor menu?

**Comment by contraspec** [comment]
* Z height, adjusted in tunables, using a feeler guage for the nozzel gap between bed. 
* i used the default setting, as the setting was/looked correct, with the position.

**Comment by andrivet** [comment]
@contraspec 
* What is the procedure to tune the z-height with the stock firmware?
* I do not think the default sensor (ADVi3++ Left Side) is correct. The sensor of the Mark II is at a very different position if I am not wrong.

**Comment by contraspec** [comment]
On the stock, z height is set during the bed level procedure,

Press bed level, then head moves to bed center, adjust the offset with 0.1mm, then press next. Once pressed next it proceeds to do the auto bed level.


The sensor on my unit is dead centre to the nozzel, and 60mm to the rear.   Blue, with the following number   LJC12A3-A-Z/BY
PNP with 5mm spacing ?

**Comment by andrivet** [comment]
Close in favor of #195

**Comment by tobashadow** [comment]
Feature request, 

add 0.01 to values on baby stepping and sensor z-height tuning, 0.04 as the lowest adjustment is not fine enough adjustment for some surfaces.

**Comment by andrivet** [comment]
@tobashadow this issue is closed. Please do not post under it. For feature request, you have to create an issue.
