### ISSUE TITLE
Aldi UK printer (HE180021) limit switch issues

### ISSUE THREAD

**Issue by MarkGodwin** [andrivet/ADVi3pp#187]
Thank you for submitting your feedback to the ADVi3++ project.

Please be sure to review the checklists below before submitting and use one of the templates. 

**It is mandatory**. If you do not comply with these rules, I will **delete** your issue.

- [x] This issue is **NOT** about support.

------------------------------------------------------------
### Bug Report

- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [x] You have tested with the **latest** version of ADVi3++ (including Beta releases)
- [x] You are able to reproduce the bug
- [x] You are able to describe step by step the process to reproduce the bug

* Exact model of your **printer**: Balco 3D Touch (www.balcolifestyle.com) from Aldi. Model number is HE180021, . Manufactured November 2018. It's not the Mk II, as far as I can tell - no auto bed levelling. It claims to be made by Winplus Australasia.
* **ADVi3++** exact version: advi3++4.0.0-alpha.3 - just built it from the sources
* Printing using **SD card** or **USB**: N/A

* Expected behaviour:
When homing, it should find the 3 axis limits and stop.

* Actual behaviour:
The Z limit switch doesn't seem to work. The home function blasts past the limit and keeps on going until I pull the plug.
Homing the X and Y axis limits work fine. Temperatures, heaters, extruder feed all seems to work fine.

I suspect the newer versions of the Wanhao i3 might use a different pin for the Z limit.
Unfortunately, I can't go back to the original Balco firmware as it's not available.

I'm going to pull the thing apart tomorrow and see if I can track the switch back to the right pin on the ATMega. My other option is to upload a simple firmware to show limit switch status, and I can try guessing some pins.

Anyhow, I'll let you know how I get on.

* Steps to reproduce:
Just hit Home Z.

**Comment by andrivet** [comment]
Very probably, you build the wrong flavor of ADVi3++: you build the BLTouch one which does not use the z endstop.

UPDATE: I am wrong, this printer is indeed different.

**Comment by ryamoo** [comment]
@MarkGoodwin couldn't you go to the "stable" release or advi3++ if you cant get 4.0 alpha 3 working - the stable version works fine on my last-year model Balco.

**Comment by MarkGodwin** [comment]
No, I built the right one. I was too lazy to take the whole thing to pieces to check the pins, so I updated the code to display the end stop pin status. Luckily there's a nice status text string and and idle loop which could be trivially re-purposed for my quick test.
The Z-stop is now on Pin 6 - same as the Mark II, according to the latest source code. So I guess the newer i3 machines _are_ Mark II, but without the automatic bed levelling.

I can compile the Mark II version, and I'm pretty certain it will work. Not totally sure about the Y axis enable pin, but I will assume that has changed too, even though the Y axis seems to work still.

I'll let you know how I get on. Someone might find this useful in the future.

**Comment by Prog72** [comment]
I've just flashed 3.0.2 to my Balco Touch and am experiencing this exact problem. I'll also look into compiling the Mk II firmware.

**Comment by andrivet** [comment]
I am building a troubleshooting page to help diagnose this kind of things #75

**Comment by MarkGodwin** [comment]
So I can confirm, my Z-limit switch is on Pin 6, but the Y-enable isn't on 2 like the source code claims for the Mk II, it's on 63 like before. So I guess this is some sort of Mk 1.5.

**Comment by MarkGodwin** [comment]
So, to be a bit clearer - the MK II firmware won't work either (also, it assumes you have a depth sensor)

**Comment by Prog72** [comment]
> So, to be a bit clearer - the MK II firmware won't work either (also, it assumes you have a depth sensor)

Thanks for the update. I shall abandon the MkII firmware compilation in that case.

**Comment by MarkGodwin** [comment]
Agonising over raising this as a separate issue, but it's likely pin related.

The Y axis seems to be working with Y-enable on pin 63, but after homing Y and then doing manual movements, I'm seeing some strange behaviour. After some manual moves of Y, when the movement ends there is a deep thundering noise coming from underneath the bed. Like it's still working the stepper, even though it's stopped. Doesn't seem to stop until you move in the reverse direction again.

I'm thinking that maybe Y-enable is on another pin, and it's floating or something like that. It seems intermittent. Any suggestions?

I guess it could just be an issue with the bleeding edge firmware?

**Comment by Prog72** [comment]
I've just changed Z_STOP_PIN to 6 in the source code for 3.0.2 and flashed the compiled firmware to my printer.

Homing now appears to be working as it should and I've successfully completed the bed levelling sequence.

EDIT: @MarkGodwin Many thanks for working out the pin assignment.

**Comment by MarkGodwin** [comment]
Good work. Big thanks to @andrivet for running the project. 👍 

I did the same, but I'm still on 4.0.0 alpha, as I don't fancy taking the face plate off again to re-flash the LCD for a third time. My Y axis hum seems to have gone away, so maybe it was down to having the USB still attached and Cura running at the same time. If it comes back, I'll open another issue.

**Comment by Prog72** [comment]
> Good work. Big thanks to @andrivet for running the project. 👍

Seconded. 👍👍

**Comment by andrivet** [comment]
This printer does not have a USB, right?

**Comment by ryamoo** [comment]
@andrivet last year's model didn't come with one. This year's model had it showing on the images (not sure if it came with it).
Last year's was an easy "fix" - the board has the solder pads/pinholes so either a port or cable could be added. I soldered a USB cable on.

**Comment by andrivet** [comment]
If one day you have a chance to take a picture of the motherboard, can you please post it here? Thanks for your help

**Comment by Prog72** [comment]
> This printer does not have a USB, right?

The latest one does thankfully.

**Comment by Prog72** [comment]
> If one day you have a chance to take a picture of the motherboard, can you please post it here? 

I opened my printer up to install the LCD enclosure and took some photos whilst inside. They're not the best quality but will hopefully show what you need. Let me know if you need a better shot of anything in particular and I'll see what I can do.

![balco_mb_1](https://user-images.githubusercontent.com/40904032/50565208-48085480-0d24-11e9-96a8-bd5b1b14a7e3.jpg)
![balco_mb_2](https://user-images.githubusercontent.com/40904032/50565211-522a5300-0d24-11e9-988c-94205c3b714c.jpg)
![balco_mb_3](https://user-images.githubusercontent.com/40904032/50565213-56567080-0d24-11e9-97f7-380e8cfcb405.jpg)
![balco_mb_4](https://user-images.githubusercontent.com/40904032/50565214-58b8ca80-0d24-11e9-99fa-0c76b37dd6e7.jpg)

**Comment by andrivet** [comment]
@Prog72 Perfect. The quality is very good. And you have a motherboard version 5.2C. Something new. Version 5.1 is Mark I, Version 5.2 is Mark II.

**Comment by Prog72** [comment]
@andrivet Glad they're useful. Interesting that the Balco printers appear to have a unique revision of the motherboard. That seems like an unnecessary expense unless there's a very good reason for it. I wonder what the C denotes.

**Comment by andrivet** [comment]
@Prog72 I assume that it is more simple for Wanhao to always go forward, especially with the development of their firmware. 

It is not easy to read under the cables, but it looks like you have the power-loss recovery, like in the Mark II. It was not there before in the i3 Plus or the Balco 2017.

**Comment by andrivet** [comment]
Support of Balco HE180021 is now in the latest sources, so I am closing this issue. But feel free to add comments if you have other technical details to add.

**Comment by MarkGodwin** [comment]
I haven't tried it yet, but it looks like you have a typo in Pins.h - seems like the same MB() define is used for both the Mk II and the Balco 2018?

Apologies if I'm wrong.

Cheers,
Mark

**Comment by andrivet** [comment]
@MarkGodwin You're right. Fixed.
