### ISSUE TITLE
Calibrating issue

### ISSUE THREAD

**Issue by sniperxnl** [andrivet/ADVi3pp#19]
Guys,

I have loaded today the firmware, and as always busy to calibrate the multiplier. Printing and messure. Now 4 walls one print and all diffrent thickness, how is that possible? 

![23561320_1462203673894494_1454935468843763977_n](https://user-images.githubusercontent.com/16321561/32858663-856a80b2-ca4c-11e7-92ee-05426ad849cb.jpg)
![23622024_1462203753894486_7762130043339029683_n](https://user-images.githubusercontent.com/16321561/32858664-8581ca56-ca4c-11e7-8dd1-c231061d5ff0.jpg)

**Comment by andrivet** [comment]
I just performed a test myself (25x25x25 mm cube, height 0.12, wall thikness 1, no top/bottom layer) with Cura 3 and I have consistant measures for the 4 walls.
Which slicer are you using, with which parameters?

**Comment by sniperxnl** [comment]
I am using s3d, 2 walls print on 0.2 with a 0.40 nozzle. Cube is 20x20x15 and print with tpu

**Comment by sniperxnl** [comment]
solved
