### ISSUE TITLE
Clear the message on the display when G4 is finished

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#192]
------------------------------------------------------------
### Feature Request

- [x] Your request is not specific to your setup but can benefit to many people
- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [x] You have provided a short but meaningful title
- [x] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [x] You have provided objective **facts**, not your personal feelings, your personal preferences.

#### Detailed description of the feature request:

* Currently, when receiving G4, the message "Sleep" is displayed on the LCD panel.
* When G4 is finished, the message remains until it is overridden by another message
* Some plugins or slicers are using G4 to better detect layer changing (see Octolaps). As a consequence, the "Sleep" message is displayed while the printer is printing and not sleeping.
* See if it is easy to modify Marlin to clear the message after the end of G4
* If not possible, maybe remove the "Sleep" message.

**Comment by Cyber-One** [comment]
Potentially the message Printing from card or printing from serial could be displayed when it is resumed....

**Comment by andrivet** [comment]
Implemented in version 4.0
