### ISSUE TITLE
Add smaller value for baby stepping and Z height setup

### ISSUE THREAD

**Issue by tobashadow** [andrivet/ADVi3pp#198]
- [x] This issue is **NOT** about support. **This is not the right place to ask for support**. You **may** get support from the [ADVI3++ Facebook page](https://www.facebook.com/advi3pp/). You can get support from the developer of ADVi3++ from its [Patreon page](https://www.patreon.com/andrivet).

------------------------------------------------------------
### Feature Request

- [x] Your request is not specific to your setup but can benefit to many people
- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [x] You have provided a short but meaningful title
- [x] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [x] You have provided objective **facts**, not your personal feelings, your personal preferences.

#### Detailed description of the feature request:

The smallest value of 0.04 is too large for some surfaces like good quality glass to get the first layer perfect. A fourth button above it for 0.01 would work much better to fine tune it better.

**Comment by andrivet** [comment]
Implemented in upcoming version 5. Values are now:
* Z-offset: 0.01, 0.10, 1.00
* Babysteps: 0.01, 0.05, 0.10
