### ISSUE TITLE
Issue - Di3++ mk2

### ISSUE THREAD

**Issue by contraspec** [andrivet/ADVi3pp#201]
Hi Sebastien,

Printing with the followin :
*  from sdcard
* v4_beta1

The following happens, in this sequence.
* start print, (all starts fine, )
* press pause as per previous msg to use pause instead of stop, head lifts up, then into far left corner.
* press the pause/resume, and extruder purges aprox 100mm of filament, then resumes to print position. 
Now this is where a possible bug shows up.
*  press the stop to cancel. It stops.
*  but now the lcd freezes up, touch the lcd buttons, it highlights and nothing happens, no beep/audio. 
* must push reset button or turn printer off to recover command of printer.

Thank you for submitting your feedback to the ADVi3++ project.

Please be sure to review the checklists below before submitting and use one of the templates. 

**It is mandatory**. If you do not comply with these rules, I will **delete** your issue.

- [ ] This issue is **NOT** about support. **This is not the right place to ask for support**. You **may** get support from the [ADVI3++ Facebook page](https://www.facebook.com/advi3pp/). You can get support from the developer of ADVi3++ from its [Patreon page](https://www.patreon.com/andrivet).

------------------------------------------------------------
### Feature Request

- [ ] Your request is not specific to your setup but can benefit to many people
- [ ] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [ ] You have provided a short but meaningful title
- [ ] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [ ] You have provided objective **facts**, not your personal feelings, your personal preferences.

Note: It is no more necessary to add "[FR]" in the title. You can, if you want, label your issue with "enhancement".

Detailed description of the feature request:

_Please provide information (such as links to web sites, blogs, technical description)._

------------------------------------------------------------
### Bug Report

- [ ] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [ ] You have tested with the **latest** version of ADVi3++ (including Beta releases)
- [ ] You are able to reproduce the bug
- [ ] You are able to describe step by step the process to reproduce the bug

* Exact model of your **printer**:
* **ADVi3++** exact version:
* Printing using **SD card** or **USB**:
* **For USB printing only** Software used to print with its exact version:

#### Description of the bug

* Expected behaviour:
* Actual behaviour:
* Steps to reproduce:
  - Do this
  - Do that

**Comment by andrivet** [comment]
Please:
* Use the template
* Do not create issues for Alpha or Beta releases. Instead, there is a dedicated issue for that: https://github.com/andrivet/ADVi3pp-Marlin/issues/195. This is explain in the Post on Patreon
