### ISSUE TITLE
Beta Hangs After Pause then Stop  

### ISSUE THREAD

**Issue by Salty-Doug** [andrivet/ADVi3pp#202]
Thank you for submitting your feedback to the ADVi3++ project.

Please be sure to review the checklists below before submitting and use one of the templates. 

**It is mandatory**. If you do not comply with these rules, I will **delete** your issue.

- [ ] This issue is **NOT** about support. **This is not the right place to ask for support**. You **may** get support from the [ADVI3++ Facebook page](https://www.facebook.com/advi3pp/). You can get support from the developer of ADVi3++ from its [Patreon page](https://www.patreon.com/andrivet).

------------------------------------------------------------
### Bug Report

- [* ] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [* ] You have tested with the **latest** version of ADVi3++ (including Beta releases)
- [* ] You are able to reproduce the bug
- [ *] You are able to describe step by step the process to reproduce the bug

* Exact model of your **printer**: Monoprice Maker Select Plus
* **ADVi3++** exact version: 4.0.0 Beta 1 (no BLTouch).
* Printing using **SD card** or **USB**: Printing from SD
* **For USB printing only** Software used to print with its exact version:

#### Description of the bug
When I press Pause then Stop during printing the screen goes to the home screen but none of the buttons respond.  The temperatures are set to zero. 

* Expected behaviour:
I should be able to go to Controls or Settings
* Actual behaviour:
The buttons light up but the software doesn't change screens.
* Steps to reproduce:
Start a print.
During the first layer press Pause.
Wait for the stage to go to the corner.
Press the Stop button.
Wait for the stage return to the part.
The screen will return to the Home screen.
Press any button and you will get light but no other response.

[FuelLineCapV3_Raft.gcode.zip](https://github.com/andrivet/ADVi3pp-Marlin/files/2948753/FuelLineCapV3_Raft.gcode.zip)

**Comment by andrivet** [comment]
Thank you for the report. But as I said already many times, do not open issues for Alpha or Beta. There is a dedicated issue for that (pinned on the top): https://github.com/andrivet/ADVi3pp-Marlin/issues/195
