### ISSUE TITLE
Support of Mark II Power Loss

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#205]
### Feature Request

- [x] Your request is not specific to your setup but can benefit to many people
- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [x] You have provided a short but meaningful title
- [x] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [x] You have provided objective **facts**, not your personal feelings, your personal preferences.

#### Detailed description of the feature request:

Wanhao Duplicator i3 Plus Mark II has a unique feature: be able to recover a print after a power loss. It is currently not implemented.

Related to #172

**Comment by andrivet** [comment]
For information, I just ordered directly from Wanhao one of those Power Loss Resume module. It should help me add this feature to ADVi3++

**Comment by abzman** [comment]
![kicad_KsWcQuzwdj](https://github.com/user-attachments/assets/428bdebf-b786-425a-a289-a0e5b93a4d90)

All this board does is detect loss of AC power some fractions of a second before the capacitors on the DC side of the power supply run out so it can save where it was before it dies.  Must be a real quick save to sd card or eeprom of the gcode line it was on or something like that

**Comment by andrivet** [comment]
Implemented in version 6.0

![PowerLoss](https://github.com/user-attachments/assets/21ea68e3-bdf8-42cc-8ac3-5defbd5b50c7)
![Power-Loss-Recovery](https://github.com/user-attachments/assets/eff3f6e0-22b7-4731-93c1-ec36b48be280)
