### ISSUE TITLE
Accelerated buttons - the longer you hold, the faster the value changes

### ISSUE THREAD

**Issue by vegar** [andrivet/ADVi3pp#211]
Thank you for submitting your feedback to the ADVi3++ project.

Please be sure to review our [code of conduct](code_of_conduct.md) and the checklists below before submitting and use one of the templates. 

**It is mandatory**. If you do not comply with these rules, I will **delete** your issue or comment. **I will be very strict**. If you persist, I may **ban** you.

- [x] This issue (or comment) is **NOT** about support. **This is not the right place to ask for support**. 
Instead, go to [ADVI3++ Community - Get Help](https://community.advi3pp.com/c/get-help). 

------------------------------------------------------------
### Feature Request

- [x] Your request is not specific to your setup but can benefit to many people
- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [x] You have provided a short but meaningful title
- [x] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [x] You have provided objective **facts**, not your personal feelings, your personal preferences.

#### Detailed description of the feature request:

For some reason, my acceleration is set to 4000 for both print and travel.
I want to change it down to 800. This requires holding in the minus button 'for ever'.

It would be nice if these buttons had some kind of acceleration. E.g. for the 5 first second, it would count one-by-one. Then it would start count ten-by-ten. 

I'm currently on the version 3.0.2

**Comment by andrivet** [comment]
Not feasible.
