### ISSUE TITLE
Display Current Babystep Offset

### ISSUE THREAD

**Issue by Baptiewright** [andrivet/ADVi3pp#213]
Feature Request

On the Babystep adjustment screen, please display the current offset.  Prusa has this on the MK3 and it lets you know exactly what number you are currently using so you can write it down for that filament rather than remembering how many presses of 0.04, 0.08 or 0.12 you used.  

Prusa
![Prusa](http://www.baptiewright.com/adv/Prusa_Live_Z.jpg)

ADVi3++
![ADVi3++](http://www.baptiewright.com/adv/adv_babysteps.jpg)

**Comment by andrivet** [comment]
Implemented in upcoming version 5.
