### ISSUE TITLE
Diagnostic routines for troubleshooting vibrations and mechanical issues

### ISSUE THREAD

**Issue by Nuramori** [andrivet/ADVi3pp#214]
### Feature Request

- [x] Your request is not specific to your setup but can benefit to many people
- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [x] You have provided a short but meaningful title
- [x] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [x] You have provided objective **facts**, not your personal feelings, your personal preferences.

#### Detailed description of the feature request:
A suggestion to add to the diagnostic menu several options. 

* Move on the x axis only, to limits repeatedly until cancelled or another option is selected. 
* Move on the y-axis only, to limits repeatedly until cancelled, leaving menu group, or another option is selected. 
* Move on the z-axis from home to a preset distance repeatedly until cancelled, leaving menu group, or another option is selected.  
* Move x and y axis together as if extruding a diagonal repeatedly until cancelled, leaving menu group, or another option selected.  

This diagnostic set would assist in tracing down mechanical issues or isolating vibration sources in order to improve printing quality.

**Comment by andrivet** [comment]
Implemented in 5.3.0
