### ISSUE TITLE
Sometimes after flashing, the LCD Panel displays a version mismatch warning

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#215]
- [x] This issue (or comment) is **NOT** about support.  
------------------------------------------------------------
### Bug Report

- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [x] You have tested with the **latest** stable version of ADVi3++
- [x] You are able to reproduce the bug
- [x] You are able to describe step by step the process to reproduce the bug

#### Description of the bug

* Exact model of your **printer**: Wanhao Duplicator i3 Plus
* **ADVi3++** exact version (Mainboard): 4.0.2
* Printing using **SD card** or **USB**: n/a
* **Do you use a BLTouch?**: no
* Expected behaviour: The firmware should detect the versions of the mainboard and of the LCD are the same
* Actual behaviour: The LCD Panel displays a version mismatch warning with LCD: 4.2, Mainboard: 4.0.2. When pressing on Continue, nothing happens.

**Comment by andrivet** [comment]
The LCD version displayed on the page is the wrong one: it is the DGUS firmware version and not the ADVi3++ LCD version.

**Comment by andrivet** [comment]
Fixed in 4.0.3

**Comment by andrivet** [comment]
Reopen because it is not completely fixed. Apparently, the way I get the version of the LCD resources is not reliable enough. Sometimes, it returns 0. So I guess, I will remove this detection mechanism in a future release.

**Comment by sparkiesweden** [comment]
I have two identical (hardware-wise) I3+ mk2 printers, one shows the missmatch error and the other don't, otherwise stuff seems to work, except that it's not possible to turn off the touch-beep on either of the printers .. a bit annoying but perhaps not related....

**Comment by redtmpusr** [comment]
Same situation as @sparkiesweden . Turning on lcd beep turns tone into almost double beep. Turned off the normal beep is there. Maker Select Plus with 4.0.3 lcd and 4.0.3 bltouch v3 mainboard. A version mis match was shown to me on fresh flash. The os reports main board as 4.0.3 and lcd as 49.2.14 . After another reboot it starts reporting lcd firmware 0
