### ISSUE TITLE
After stopping a print the X, Y, and Z axis will all move when Z jog is pressed. 

### ISSUE THREAD

**Issue by Salty-Doug** [andrivet/ADVi3pp#219]
- [X] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [X] You have tested with the **latest** stable version of ADVi3++
- [X] You are able to reproduce the bug
- [X] You are able to describe step by step the process to reproduce the bug

#### Description of the bug

* Exact model of your **printer**: Monoprice MSP. 
* **ADVi3++** exact version (Mainboard): 4.0.3 with BLTouch. 
* Printing using **SD card** or **USB**: SD card. 
* **For USB printing only**: Software used to print with its exact version:
* **Do you use a BLTouch?**: If yes, exact version of the BLTouch: V2.1
* Expected behaviour: Only the Z axis should move and the system should not lock up. 
* Actual behaviour: All 3 axis moves and the only way to stop the motion is to power off or push the reset button. 
* Steps to reproduce:
  - Start a print from an SD card. 
  - Wait until the the printing begins. 
  - Press the stop button twice. 
  - Wait until the motion stops. 
  - Go to the Move menu and press the Z up arrow.

**Comment by andrivet** [comment]
I am able to reproduce this behavior. Thank you for the precise bug report,
Apparently (at least with my printer), you do have to press Stop two time to have this incorrect behavior.

**Comment by Salty-Doug** [comment]
You are welcome.
I’m glad to help with the code.  I really like using it.

**Comment by andrivet** [comment]
Fixed in 4.0.5

**Comment by Salty-Doug** [comment]
@andrivet When do you plan on building 4.0.5?
