### ISSUE TITLE
ADVi3++ on Wanhao D9

### ISSUE THREAD

**Issue by davidbue** [andrivet/ADVi3pp#220]
Dear Sebastian Andrivet,

Fist, let me take this opportunity to convey my deepest appreciation for your contribution to the open source 3D printing community.

Now, I have a simple question that I have searched the web the for, for last two weeks now, The display hardware of the Wanhao D9 looks identical to the Wanhao i3, least when I compare our D9 display to images of the i3 display from the web. I cannot though, find any information as to whether the ADVi3++ display firmware is compatible with the Wanhao D9 display.

I can see that this question has been asked before (issue #155). You also elude on your patreon that support for the D9 is coming. Yet, I cannot understand if the firmware as for now is compatible. Can you confirm whether this is the case?

Sincerely,
  David

**Comment by andrivet** [comment]
As explained in this repository, do not use it for support requests. This place is only for feature requests and bugs reporting. The right place for support requests in on [ADVi3++ Community](https://community.advi3pp.com/).
