### ISSUE TITLE
M851 should accept all offset arguments, not just Z offset

### ISSUE THREAD

**Issue by prenetic** [andrivet/ADVi3pp#238]
I have noticed the M851 response only confirms/applies the value given for the Z offset, and ignores the values specified for X and Y. Since the ADVi3pp firmware does already support a "custom" offset profile in addition to the two built-in offset profiles, **it would be beneficial if all M851 arguments were accepted, and subsequently saved to the "custom" profile**. Currently, the only way to specify X and Y offset values are via the touch interface on the LCD.

Current behavior:
```gcode
Send: M851 X-24 Y-38
Recv: echo:Probe Z Offset: 0.00
Recv: ok
Send: M503
[...]
Recv: echo:Z-Probe Offset (mm):
Recv: echo:  M851 Z0.00
[...]
Recv: ok
```

I'm running ADVi3pp v4.0.5 on a Monoprice Maker Select Plus with a BLTouch V3.0, which I am restoring and making incremental upgrades on for a friend of mine. One of the things I wanted to include for them was a .gcode file that had all of the optimized parameters specific to this machine so that if SRAM/EEPROM values needed to be restored to a known-good configuration, this file could be run and minimal effort or knowledge would be required to get up and running again. The only missing piece to this solution is full support of M851 per Marlin FW documentation (link below).

I also ran into a corruption issue this morning where multiple parameters in EEPROM were zeroed out, leading me to believe the extruder driver had died as no voltage was applied to the extruder, so being able to quickly restore all mission-critical parameters from a known-good configuration would have saved me a couple hours of troubleshooting as well. It's just one less thing to remember during initialization.

https://marlinfw.org/docs/gcode/M851.html - Marlin FW documentation for M851, which supports X, Y, and Z offset values for a probe.

**Comment by andrivet** [comment]
I am not able to reproduce this. I get:

```
M851
  M851 X1.50 Y-42.70 Z0.00 ; (mm)
ok
M851 X-24 Y-38
ok
M851
  M851 X-24.00 Y-38.00 Z0.00 ; (mm)
ok
```

I assume that this bug was fixed when merging Marlin's upstream code.
