### ISSUE TITLE
G92 E0, reverses extruder to 0, not Zero after purge.

### ISSUE THREAD

**Issue by contraspec** [andrivet/ADVi3pp#240]
Thank you for submitting your feedback to the ADVi3++ project.

Please be sure to review our [code of conduct](code_of_conduct.md) and the checklists below before submitting and use one of the templates. 

**It is mandatory**. If you do not comply with these rules, I will **delete** your issue or comment. **I will be very strict**. If you persist, I may **ban** you.

- [ ] This issue (or comment) is **NOT** about support. **This is not the right place to ask for support**. 
Instead, go to [ADVI3++ Community - Get Help](https://community.advi3pp.com/c/get-help). 

------------------------------------------------------------
### Feature Request

- [ ] Your request is not specific to your setup but can benefit to many people
- [ ] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [ ] You have provided a short but meaningful title
- [ ] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [ ] You have provided objective **facts**, not your personal feelings, your personal preferences.

#### Detailed description of the feature request:

_Please provide information (such as links to web sites, blogs, technical description)._

------------------------------------------------------------
### Bug Report

- [x] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [x] You have tested with the **latest** stable version of ADVi3++
- [x] You are able to reproduce the bug
- [x] You are able to describe step by step the process to reproduce the bug

#### Description of the bug

* Exact model of your **printer**:
* **ADVi3++** exact version (Mainboard):
* Printing using **SD card** or **USB**:
* **For USB printing only**: Software used to print with its exact version:
* **Do you use a BLTouch?**: If yes, exact version of the BLTouch
* Expected behaviour:
* Actual behaviour:
* Steps to reproduce:
  - Do this
  - Do that

Wanhao i3 Plus MK2 - v5.4
ADVi3++ 4.0.6
SD Card & Cura 4.5.0

_Expected behavior_
G92 E0 ; Zero the extruder 

_Actual behavior_

Start Script:
G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
G28 X0 Y0 ;move X/Y to min endstops
G28 Z0 ;move Z to min endstops
G92 E0 ;zero the extruded length
G1 F250 E10 ;extrude 10 mm of feed stock
G1 Z6 F3000 ; lift
G1 X40 Y0 F5000 ; Jump binder clip
G1 Z0.2 F5000 ; get ready to prime
G92 E0 ;zero the extruded length
G1 F300 E8 ;extrude 8 mm of feed stock
G92 E0 ;zero the extruded length again
G1 F400 X50 F1000 E10  ; prime nozzle 10mm
G92 E0 ;zero the extruded length again
G1 X60 F5000 ; quick wipe
G1 F{travel_speed}  ;Put printing message on LCD screen
M117 Printing...

when G92 E0 command is given the filament retracts, and not Zero the extruder.

previous version used on printer 4.0.2 this work fine.

**Comment by andrivet** [comment]
Please follow the template. It is mandatory (as written in it).
