### ISSUE TITLE
Is there any possibility to add power resume function.

### ISSUE THREAD

**Issue by ahmadhanis** [andrivet/ADVi3pp#242]
Thank you for submitting your feedback to the ADVi3++ project.

Please be sure to review our [code of conduct](code_of_conduct.md) and the checklists below before submitting and use one of the templates. 

**It is mandatory**. If you do not comply with these rules, I will **delete** your issue or comment. **I will be very strict**. If you persist, I may **ban** you.

- [ ] This issue (or comment) is **NOT** about support. **This is not the right place to ask for support**. 
Instead, go to [ADVI3++ Community - Get Help](https://community.advi3pp.com/c/get-help). 

------------------------------------------------------------
### Feature Request

- [ ] Your request is not specific to your setup but can benefit to many people
- [ ] You have checked that you are not creating a **duplicate** of an existing (maybe closed) request (use the search)
- [ ] You have provided a short but meaningful title
- [ ] You have provided enough information (such as links to web sites, blogs, technical description) so that anyone can understand what you are talking about. Just any only a title is not enough.
- [ ] You have provided objective **facts**, not your personal feelings, your personal preferences.

#### Detailed description of the feature request:

_Please provide information (such as links to web sites, blogs, technical description)._

------------------------------------------------------------
### Bug Report

- [ ] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [ ] You have tested with the **latest** stable version of ADVi3++
- [ ] You are able to reproduce the bug
- [ ] You are able to describe step by step the process to reproduce the bug

#### Description of the bug

* Exact model of your **printer**:
* **ADVi3++** exact version (Mainboard):
* Printing using **SD card** or **USB**:
* **For USB printing only**: Software used to print with its exact version:
* **Do you use a BLTouch?**: If yes, exact version of the BLTouch
* Expected behaviour:
* Actual behaviour:
* Steps to reproduce:
  - Do this
  - Do that

**Comment by andrivet** [comment]
Close because it is a duplicate and does not follow the rules for feature requests.
