### ISSUE TITLE
Y missing steps

### ISSUE THREAD

**Issue by sniperxnl** [andrivet/ADVi3pp#26]
Guys, I have done serval prints on different location on the bed, and the y axis have a missing step always on the same height,. I have already checked all the belts. The bed is smooth no cable is stuck. Looks like it happend after this new firmware

**Comment by Multiplxd** [comment]
I flashed my machine with 1.0,1 and am now having the same issue with either jitter or missing steps on the Y axis

**Comment by sniperxnl** [comment]
Why is it closed? Any solution?

**Comment by andrivet** [comment]
Because if you flash another (stock) firmware and still have the same problem, it is not related to the firmware.

**Comment by sniperxnl** [comment]
I have it only on the marlin firmware

**Comment by Multiplxd** [comment]
I flashed over from the latest wanhao where I didn't have this issue.

**Comment by sniperxnl** [comment]
Hai @andrivet  found the issue, my new SD card was the issue.

**Comment by andrivet** [comment]
Happy to learn that!
