### ISSUE TITLE
Diagonal movement during manual leveling

### ISSUE THREAD

**Issue by guyvia** [andrivet/ADVi3pp#261]
When adjusting the corners, it will move along x and then y to go corner to corner, instead of moving at a 45 degree angle. This is certainly not a huge issue, but it would be a quality of life improvement for those of us without auto-leveling.

**Comment by andrivet** [comment]
Do not see the point of the issue. What's wrong with the current behaviour?

**Comment by cjastone** [comment]
Having upgraded recently from 4.0.6, this used to be the old behaviour.  It's much faster when performing a series of small, iterative adjustments when trying to get the bed "juuust right".

I'm not sure with which version this behaviour was changed, however it has certainly increased the time taken for these movements.

**Comment by andrivet** [comment]
Closing in favour of #289
