### ISSUE TITLE
Laser on Fan PWM frequency too slow

### ISSUE THREAD

**Issue by zkarolyi** [andrivet/ADVi3pp#269]
### Bug Report

- [X] You have checked that you are not creating a **duplicate** of an existing (maybe closed) issue (use the search)
- [X] You have tested with the **latest** stable version of ADVi3++
- [X] You are able to reproduce the bug
- [X] You are able to describe step by step the process to reproduce the bug

#### Description of the bug

* Exact model of your **printer**: Wanhao Duplicator i3 Plus
* **ADVi3++** exact version (Mainboard): 5.0.1
* Printing using **SD card** or **USB**: SD
* **Do you use a BLTouch?**: No
* Expected behaviour: Setting Fan speed (M106 S<0-255>) sets laser power
* Actual behaviour: PWM freq is to slow, laser just switches on/off slowly
* Steps to reproduce:
  - Connect a laser module to printer: external 12V power and Fan PWM output to laser PWM input.
  - Try to engrave with half power (M106 S125)
  - Laser will draw a dashed line

Maybe the solution of the #107 caused this, because the FAN_SOFT_PWM is too slow.
The laser PWM max freq is about 20kHz.

Connection details:
External 12V power to the laser power.
Fan gnd pin to external power gnd.
Fan pwm signal to laser pwm input with a resistance divider (24V->12V).

**Comment by andrivet** [comment]
This is not a bug. This firmware was never intended to work with a Laser.
