### ISSUE TITLE
Warn if manual bed leveling is attempted while extruder is hot

### ISSUE THREAD

**Issue by galfisk** [andrivet/ADVi3pp#287]
### Did you check that your request is not a duplicate?

Yes, I have checked and this is a new request.

### Is your request specific to your setup only or can it benefit to many people?

My request will benefit to many people.

### Is your feature request related to a problem? Please describe.

If the bed is too high, manual leveling pushes the extruder into the print surface. If the extruder is hot, it can melt divots in a plastic print bed surface, such as the original Wanhao printing surface sheet. 

### Describe the feature you want

When invoking manual bed leveling while the extruder is hot, there should be a warning that this could damage a plastic print surface. 
If possible, there should then be three options: cancel, continue anyway, or cooldown&continue. People with glass beds might not care to wait.

### Additional context

I'd post photos, but I've replaced our old pitted print surfaces, and I couldn't find a good reference online.
I don't know the exact max temperature limit, but 100°C should be a conservative and safe temperature for the original Wanhao print surface.

### Have you provided enough and precise information?

Yes, I have provided precise information in the Additional context box.

**Comment by andrivet** [comment]
Added to version 5.4
