### ISSUE TITLE
BLTouch - warning on transposed black and white wires

### ISSUE THREAD

**Issue by MartynWilliams** [andrivet/ADVi3pp#293]
Hi,
I noticed that after flashing 5.4.0 i'm getting the warning that the black and white wires may be transposed. 
I have checked the wiring and all is correct. This issue was not reported on previous firmware versions.

The BLTouch works flawlessly.

Aldi Cocoon Plus
5.1 mainboard
BLTouch Smart 3.x

Regards
Martyn

**Comment by andrivet** [comment]
Workaround in version 5.4.2. Will be fixed later

**Comment by Snipeye** [comment]
@andrivet I've installed the update and my BLTouch is now blinking blue every second or so, is this intended?
EDIT: This was resolved with a restart, must have just been in a weird state.

**Comment by MartynWilliams** [comment]
Confirmed that  workaround now displays the correct values.

**Comment by andrivet** [comment]
Fixed in version 5.5.0 with code adapted from M43
