### ISSUE TITLE
If print menu is accessed while printer is moving, it shows as if it's printing

### ISSUE THREAD

**Issue by galfisk** [andrivet/ADVi3pp#294]
### Did you check that your report is not a duplicate?

Yes, I have checked and this is a new bug not previously reported.

### Bug Description

If the printer is moving, as the result of a previous command on the LCD, and the user accesses the "Print" menu, the printer will show the printing stats menu rather than the file browser.

### Expected behavior

Since the printer is not actually processing a print, I'd expect it to go to the file browser.

### Actual behavior

It shows the printing stats and temperatures, and the pause, stop, etc buttons. If a file has previously been selected for printing, that file name is shown in the window.

### Steps to Reproduce

1. Choose "Leveling"
2. Choose "Manual"
3. Choose the "3" leveling point
4. While the printer is moving to there, choose the check mark, quickly press "back" and then "print" before the move has completed.

### Version of ADVi3++ Firmware

5.4.1

### Printer model

Wanhao Duplicator i3 Plus

### Additional information & file uploads

This happened easier before diagnoal motion was implemented in the manual bed leveling routine, but it can still happen to an experienced and quick-fingered user. A "please wait for the move to finish" screen, like what's shown when trying to cancel an ongoing vibrations tuning, would prevent this.

**Comment by andrivet** [comment]
Fixed in version 5.5
