### ISSUE TITLE
Manual jog controls disturb homing function, triggering "Homing failed" hardware error

### ISSUE THREAD

**Issue by galfisk** [andrivet/ADVi3pp#296]
### Did you check that your report is not a duplicate?

Yes, I have checked and this is a new bug not previously reported.

### Bug Description

Homing can be interrupted by using the manual jog controls, and this triggers the  "Homing failed" hardware error

### Expected behavior

I expect either homing to be canceled, or the jog controls to be disabled during homing. Preferrably the homing should be canceled, that way the directional controls can be used as panic buttons if homing is pressed by mistake and would have caused a problem.

### Actual behavior

The jog controls override the motion of the homing command, triggering a hardware error

### Steps to Reproduce

1. Go to Controls-Move
2. Press the Homing button for any axis (or Home *)
3. While the printer is homing, press and hold a directional control to move an axis in the opposite direction
4. When you let go of the directional control, the Homing failed error is shown

### Version of ADVi3++ Firmware

5.4.1

### Printer model

Wanhao Duplicator i3 plus, tested on 5.1 mainboard

**Comment by andrivet** [comment]
Fixed in version 5.5
