### ISSUE TITLE
Option to enable fast probing using bltouch 

### ISSUE THREAD

**Issue by MartynWilliams** [andrivet/ADVi3pp#303]
### Did you check that your request is not a duplicate?

Yes, I have checked and this is a new request.

### Is your request specific to your setup only or can it benefit to many people?

My request will benefit to many people.

### Is your feature request related to a problem? Please describe.

Probing of the bed during the leveling process take significant time to complete

### Describe the feature you want

Is it possible to include an option to speed up bed probing by not stowing the probe tip during moves to each of the probe positions.

### Additional context

Recently helped the local Mens Shed to setup an ender 3 with BLTouch. 
This feature is included on the professional software release for the ender 3 written by Miguel Risco-Castillo.
Thought it might be a consideration for ADVI3++

https://github.com/mriscoc/Ender3V2S1

### Have you provided enough and precise information?

Yes, I have provided precise information in the Additional context box.

**Comment by andrivet** [comment]
Merge with #306
