### ISSUE TITLE
Aldi Balco 3D Printer (model HE180021) - BL Touch installation wiring Image is incorrect

### ISSUE THREAD

**Issue by MartynWilliams** [andrivet/ADVi3pp#304]
### Did you check that your report is not a duplicate?

Yes, I have checked and this is a new bug not previously reported.

### Bug Description

BL Touch installation wiring Image for the Aldi Balco 3D Printer (model HE180021) is incorrect and does not match the wiring table.

### Expected behavior

Picture should match the wiring table. 

### Actual behavior

The image of ther Aldi Balco 3D Printer (model HE180021) seems to be same as the Wanhao clone wiring picture.

### Steps to Reproduce

Not Applicable

### Version of ADVi3++ Firmware

5.4.2

### Printer model

Not applicable

### Mods

Not applicable

**Comment by andrivet** [comment]
Thanks for reporting this mistake. This is fixed.
