### ISSUE TITLE
User Manual Site BROKEN

### ISSUE THREAD

**Issue by EhRabz** [andrivet/ADVi3pp#305]
Oops, something went wrong...
Invalid email / username or password.

Even when im 100% , and logged in.

**Comment by andrivet** [comment]
You are probably following a wrong link. But you are not telling which one.

**Comment by andrivet** [comment]
I closed it because you provided no information. You are not following the required template.

**Comment by andrivet** [comment]
You can't just say "BROKEN", without telling me what it is about, what is broken, etc. I can't guess. So if you provide information and explain exactly what is the problem, I will reopen the issue.

**Comment by EhRabz** [comment]
Anytime I go to log in. I get hit with Oops, something went wrong...
Invalid email / username or password. even though the same username and password are used to log into the forum.

**Comment by andrivet** [comment]
Are you a sponsor of the project ?

**Comment by EhRabz** [comment]
Oh didn't realize its behind a paywall now, but seems like I can't pledge to you for some reason.

**Comment by andrivet** [comment]
It is written on the first page: 

Note: Full access to this User Manual is only provided to active sponsors of [the project on Patreon](https://www.patreon.com/bePatron?u=6504486).
