### ISSUE TITLE
G-Code M114 response breaks Octolapse

### ISSUE THREAD

**Issue by Damien0505** [andrivet/ADVi3pp#317]
### Did you check that your report is not a duplicate?

Yes, I have checked and this is a new bug not previously reported.

### Bug Description

When responding to M114, ADVi3++ (5.4.2) responds with "Extruder" for the extruder position instead of "E"

Marlin example:
> M114
X:0.00 Y:127.00 Z:145.00 E:0.00 Count X: 0 Y:10160 Z:116000
ok

ADVi3++ example:
Send: M114
Recv: X:-2.00 Y:0.00 Z:-0.17 Extruder:0.00 Count X:-160 Y:0 Z:0
Recv: ok

### Expected behavior

Is is expected to report M114 is the common Marlin output format.

### Actual behavior

It reported with "Extruder" instead of "e"

### Steps to Reproduce

Go to terminal in Octoprint
Enter "M114"

### Version of ADVi3++ Firmware

5.4.2

### Printer model

Cocoon Create 3D Touch

### Bed Leveling

BLTouch (genuine)

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

Examining /Marlin/src/core/language.h I found the following on line 359:

#define STR_E "Extruder" // @advi3++

**Comment by Damien0505** [comment]
Hi Sebastien,

Having downloaded the code, edited "Extruder" back to "E", compiled and uploaded the firmware to my printer everything now appears to be working correctly including Octolapse.

While I have not noticed an negative effect of this change, I am not sure if there is any other effect reverting back to "E" may have.

Many thanks for ADVi3++, I am loving it!

**Comment by andrivet** [comment]
I indeed changed "E" to "Extruder" because it was not really user friendly but I do not anticipated this side effect. I will revert to "E" in the next release.

**Comment by andrivet** [comment]
Fixed in version 5.5.0
