### ISSUE TITLE
unable to access documentation on https://manual.advi3pp.com/

### ISSUE THREAD

**Issue by Clumsy-Coder** [andrivet/ADVi3pp#325]
### Did you check that your report is not a duplicate?

Yes, I have checked and this is a new bug not previously reported.

### What kind of report is it?

There is something wrong in the documentation.

### Describe the issue

Unable to access documentation on https://manual.advi3pp.com/

Steps:
1. create account on https://community.advi3pp.com/ and activate account
2. go to https://manual.advi3pp.com/
3. Go to https://manual.advi3pp.com/en/how-to-flash
4. login using credentials from https://community.advi3pp.com/
5. Error message `Oops, something went wrong`

![image](https://user-images.githubusercontent.com/19594044/211023117-80a4b4a1-4c67-4201-99be-f2ef5644555b.png)

### Have you provided enough and precise information?

Yes, I have provided precise information.

**Comment by andrivet** [comment]
The full User Manual is only accessible to active supporters of the project on Patreon. If you are an active supporter and have issues accessing the manual, please send me a message on ADVi3++ Community.
