### ISSUE TITLE
Extruder tuning - measurement image missing 5.7.x

### ISSUE THREAD

**Issue by MrSJDDevelopments** [andrivet/ADVi3pp#334]
### Did you check that your report is not a duplicate?

Yes, I have checked and this is a new bug not previously reported.

### Bug Description

Minor graphical fault, While tuning extruder ADVi3++ 5.7.x. first asks the following....

"Measure 120mm of filament above the extruder and set a mark as shown in the picture"

The picture is missing

### Expected behavior

Tuning mechanics worked as expected

### Actual behavior

Tuning mechanics worked as expected

### Steps to Reproduce

From main screen clicked tuning, 
Clicked Extruder,
Found Image Missing

### Version of ADVi3++ Firmware

5.7.x

### Printer model

Aldi Balco 3D Printer UK (5.2C) & Wanhao Duplicator i3 Plus Mark II (5.4)

### Bed Leveling

BLTouch (genuine)

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

### Additional information & file uploads

*

**Comment by MrSJDDevelopments** [comment]
I have tried refreshing the LCD segment on both printers with no change.

**Comment by andrivet** [comment]
Fixed in 5.8.0
