### ISSUE TITLE
To be able to cycle back and forth between the first and last setup screens on the temperature presets

### ISSUE THREAD

**Issue by MauroGil66** [andrivet/ADVi3pp#345]
### Did you check that your request is not a duplicate?

Yes, I have checked and this is a new request.

### Is your request specific to your setup only or can it benefit to many people?

My request will benefit to many people.

### Describe the feature you want

When you are in temperature preset 1 and want to go for preset 5, you cannot click on the left arrow to go straight for it. You need to go through presets 2, 3 and 4. It's the same thing when you want to come back from preset 5 to 1; you need to pass all of them in the way back. The easiest way would be to allow a jump from 1 to 5 back and forth. The arrows are already there. It is just a matter to set them accordingly.
<img width="941" alt="temperature preset" src="https://github.com/andrivet/ADVi3pp/assets/32619520/cebcdbaf-b4cb-4a5b-b817-67b71314cc01">

### Additional context

Could be implemented on version 6

### Have you provided enough and precise information?

Yes, I have provided precise information in the Additional context box.

**Comment by andrivet** [comment]
Implemented in version 6.0
