### ISSUE TITLE
Element width rendering in Sketch app

### ISSUE THREAD

**Issue by taligentx** [andrivet/ADVi3pp#349]
### Did you check that your report is not a duplicate?

Yes, I have checked and this is a new bug not previously reported.

### Bug Description

At least as of Sketch.app 100.3, some element widths are too small and overflow to two lines - a few sample screens are attached below from the 5.8.0 version of LCD-Panel/Masters/ADVi3++5 LCD-Panel.sketch. 

Interestingly, the same elements render correctly in Lunacy. Typically, the width for these elements is short by 1 pixel and causes an overflow. Font is Avenir Next.

<img width="689" alt="Screen Shot 2024-09-16 at 8 25 41 PM" src="https://github.com/user-attachments/assets/fa9db88d-7f86-40b7-983f-6b9ebca4b68a">

<img width="692" alt="Screen Shot 2024-09-16 at 8 28 46 PM" src="https://github.com/user-attachments/assets/a1a29172-e11c-41c7-865d-6ed17e2b1082">

<img width="776" alt="Screen Shot 2024-09-16 at 8 28 21 PM" src="https://github.com/user-attachments/assets/306e9d9e-535c-435a-b471-dfd7ada4a942">

<img width="766" alt="Screen Shot 2024-09-16 at 8 27 59 PM" src="https://github.com/user-attachments/assets/3d1217fe-c1f3-4f86-9cbe-cc25444bccf2">

<img width="704" alt="Screen Shot 2024-09-16 at 8 27 39 PM" src="https://github.com/user-attachments/assets/bd0f3560-1a5e-42df-8286-43cb608937ca">

<img width="780" alt="Screen Shot 2024-09-16 at 8 26 39 PM" src="https://github.com/user-attachments/assets/d77d4f86-fd7e-4d15-aa13-19ada6df8fcc">

<img width="776" alt="Screen Shot 2024-09-16 at 8 26 05 PM" src="https://github.com/user-attachments/assets/e3e1513e-ebc3-435e-a5ac-0c0b71e09024">

### Expected behavior

Elements widths should render correctly in the application that originated the .sketch file format.

### Actual behavior

As described.

### Steps to Reproduce

Open ADVi3++5 LCD-Panel.sketch in Sketch.app (macOS).

### Version of ADVi3++ Firmware

5.8.0

### Printer model

n/a

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by andrivet** [comment]
Thank you for this very detailed bug report. I will do my best to fix those. I am not using Sketch but Lunacy, so some of the problems may be related to that.

**Comment by andrivet** [comment]
Fixed in  6.0.0
