### ISSUE TITLE
[FR] Correct the colors on preheat screen

### ISSUE THREAD

**Issue by agentnoise** [andrivet/ADVi3pp#35]
Everywhere else in the interface the bedtemp is blue and the heater temp is red.  On the preheat screen that is reversed for some reason

**Comment by andrivet** [comment]
Icons are also at the wrong place. Some dyslexia problem.

**Comment by andrivet** [comment]
Fixed in version 2.0.1

**Comment by TTVert** [comment]
Dumb question but why not have them red while heating and blue while cooling?  A quick visual to determine status.
