### ISSUE TITLE
Widget LED element marked as exportable

### ISSUE THREAD

**Issue by taligentx** [andrivet/ADVi3pp#350]
### Did you check that your report is not a duplicate?

Yes, I have checked and this is a new bug not previously reported.

### Bug Description

As of 5.8.0, Widgets/LED/Output is marked as exportable in `ADVi3++5 LCD-Panel.sketch`:
<img width="795" alt="Screen Shot 2024-09-16 at 8 46 31 PM" src="https://github.com/user-attachments/assets/e01ed3b4-169c-4138-bb5b-d1a2447b5afd">

During export, this causes the Sketch app to create the following file in its own subdirectory in the export directory: Widgets/LED/Output.png:
<img width="741" alt="Screen Shot 2024-09-16 at 8 57 26 PM" src="https://github.com/user-attachments/assets/59e8d88c-5a72-465e-8454-31b7546195d7">

<img width="729" alt="Screen Shot 2024-09-16 at 9 20 09 PM" src="https://github.com/user-attachments/assets/2f55489e-67bb-41ec-9845-846e119b3f8c">

No other elements in the Widgets panel are marked as exportable and do not create files in their own subdirectories - for example, there is no export PNG set for this element:
<img width="798" alt="Screen Shot 2024-09-16 at 8 56 46 PM" src="https://github.com/user-attachments/assets/6623cb2d-efd1-457e-986f-d1f536206f98">

This also causes an error message when running Scripts/create-release.sh:

`WARNING: Unknown file (...)/LCD-Panel/Export/Widgets/LED/Output.png`

### Expected behavior

The .sketch file should not export Widgets/LED/Output.png

### Actual behavior

As described.

### Steps to Reproduce

Export all images from `ADVi3++5 LCD-Panel.sketch`

### Version of ADVi3++ Firmware

5.8.0

### Printer model

n/a

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by andrivet** [comment]
Thank you for this very detailed bug report. I will do my best to fix this. I am not using Sketch but Lunacy, so it may be related to that.

**Comment by andrivet** [comment]
Fixed in 6.0.0
