### ISSUE TITLE
Long filenames displace percent complete status

### ISSUE THREAD

**Issue by chschmit** [andrivet/ADVi3pp#36]
------------------------------------------------------------
- Description: Filenames that are too long prevent the percent complete status from showing
- Expected behaviour: The percent complete is visible regardless of the length of the filename.
- Actual behaviour: The filename likely forces the percent complete status out of view.
- Steps to reproduce:
  - While printing the filename and percent complete status are normally visible on the temperature graph, if the filename is too long, the percent complete status is missing.

**Comment by Martin-Dolan** [comment]
Haha I was just about to ask if there *was* a percent complete display. I guess all my file names are way too long because I've never seen it!

**Comment by andrivet** [comment]
I am not able to reproduce. Can you give an example? "Filenames that are too long" is a little bit vague. Close for the moment. Do not hesitate to reopen if you add more details

**Comment by chschmit** [comment]
As of 3.0 Beta 1, the percentage status is visible AND I'm using longer filenames (at least 30 characters long). Previously if the filename and extension had more than 18 characters the percentage status didn't show up. Thank you.

**Comment by adobito** [comment]
@andrivet I am right now printing `ZeroOffset_Bracket.gcode` in 2.1.0 and only one digit of the progress percentage. Seems to me like any more digits after that could potentially make it so the progress number just doesn't show. 

I understand from what @chschmit posted this might be fixed or harder to run into in 3.0 Beta updates, but I haven't tried those yet.
