### ISSUE TITLE
Cancel Auto PID

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#39]
Put a back arrow on the screen if the user wants to exit from it before finished. Right now you have to turn the machine off to exit prematurely.

**Comment by aoifefahey** [comment]
The same issue occurs when trying to exit the e-step tuning. I'm not sure if the problem is related or not.

**Comment by f0lie** [comment]
I have the same issue right now. ~~The PID tuner is seemly doing nothing and there isn't a way to exit it.~~

~~Maybe the PID tuning whole another issue.~~

Turns out the graph was just frozen. #78

**Comment by andrivet** [comment]
Implemented in version 4.0.0. e-steps tuning cancellation is moved to #177
