### ISSUE TITLE
[FR] BLTouch

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#4]
### Feature Request

Give instructions to install [BLTouch](https://www.antclabs.com/bltouch) and enable it in the firmware. There are apparently some room (i.e. enough pins) on the i3 Plus motherboard.

![img_2249](https://user-images.githubusercontent.com/981049/31935493-4383d558-b8af-11e7-80e6-d093dc4aea96.JPG)

**Comment by sniperxnl** [comment]
That would be nice to add to the I3+, is there are workout how to connect it to the mainboard already?

**Comment by weidercs** [comment]
Do you want me to add some instructions here or will you just take it from my fork?

**Comment by andrivet** [comment]
I will take the instructions (and configuration) from your fork.

**Comment by alexten9** [comment]
weidercs i took your files loaded to printer and when I do G28 Z just moves up and all others go home

**Comment by alexten9** [comment]
weidercs i was able to use your files can you point to the next step on how to tune it in.

**Comment by andrivet** [comment]
Implemented in release 3.0.0
