### ISSUE TITLE
[FR] Fillament runout sensor

### ISSUE THREAD

**Issue by sniperxnl** [andrivet/ADVi3pp#42]
Is it possible to add that?

**Comment by andrivet** [comment]
Please be more precise. Which runout sensor? To evaluate if I can add something into the firmware, I have to know what.

**Comment by jonathanweinberg** [comment]
Usually a filament runout sensor is just a NC (normally closed) switch. Here is an example: https://www.thingiverse.com/thing:2665162

When it goes open, Marlin registers the filament has run out and pauses the print. Scroll down to “Filament Runout Sensor”: http://marlinfw.org/docs/configuration/configuration.html

**Comment by andrivet** [comment]
How do you plan to connect it to the motherboard?

**Comment by jonathanweinberg** [comment]
Sorry, I was just passing through and noticed a question I could help clarify. Don’t even own a Plus.

**Comment by andrivet** [comment]
Closed because no (useful) feedback or information
