### ISSUE TITLE
Fan speed on the print temperature log slow to update

### ISSUE THREAD

**Issue by rippledabs** [andrivet/ADVi3pp#45]
Update: Upon more use, I realized that the screen does update to show the fan speed, but it is slow to update and doesn't capture the fan in real time. I have autocooling turned on that adjusts the fan speed for bridging, and most of the time, the fan turns ON and then Off before the screen can even register.

**Comment by andrivet** [comment]
I am not able to reproduce what you see. In my test, the update is quick (1/2 second). Can you give more details:

- Exact version of ADVi3++?
- Are you printing from the SD card or using USB?
- In the case of USB, with which software (name and version)?
- How do you change the fan speed? In the printing software? In a plug-in?

**Comment by andrivet** [comment]
Close because no feedback. Be free to comment if you want to reopen issue
