### ISSUE TITLE
Correct documentation for installing LCD data

### ISSUE THREAD

**Issue by pigrew** [andrivet/ADVi3pp#48]
On my i3+, once the data is loaded into the LCD controller, the display remained white.

The user manual said that the screen should be black: "After around 2 or 3 minutes, the screen turns black".

A few minutes after the screen turned white, it turned grey. It seems to be a screensaver of sorts, it became white again after tapping the screen.

**Comment by voretaq7** [comment]
Mine went to black - might have something to do with the actual version of the firmware on the LCD controller which determines if you get a black or white screen?

"Wait until there are no more images appearing" may be a better way to phrase this?

**Comment by andrivet** [comment]
Done in release 2.1
