### ISSUE TITLE
LCD print menu short filename (8.3) display bug

### ISSUE THREAD

**Issue by spma123** [andrivet/ADVi3pp#50]
In the print from sd card menu filenames aren't displayed for files with short file name (8.3, eg.: 12345678.GCO). M20 works correct. 
![image](https://user-images.githubusercontent.com/35433216/34920420-b125e2dc-f972-11e7-8e8c-44419fb3e98f.png)

**Comment by andrivet** [comment]
Fixed in version 3.0.0
