### ISSUE TITLE
[FR] Support of LJ18A3-8-Z/BX 8mm Approach Sensor

### ISSUE THREAD

**Issue by HKPaul** [andrivet/ADVi3pp#51]
### Feature Request

Support of LJ18A3-8-Z/BX 8mm Approach Sensor:
https://www.aliexpress.com/item/Promotion-LJ18A3-8-Z-BX-8mm-Approach-Sensor-NPN-NO-Switch-DC-6-36V/32623086326.html

**Comment by andrivet** [comment]
Wrong account...
