### ISSUE TITLE
[FR] USB Serial Diagnostics

### ISSUE THREAD

**Issue by kizza42** [andrivet/ADVi3pp#56]
### Feature Request
Would it be possible to access:
-USB serial settings  (Baud Rate selection?)
-Printer Buffer (Display lines of gCode remaining in buffer)

I am having an issue where from time to time the printer will seize up when it is controlled by Octoprint, when it happens, the extruder leaves a large bubble in the material from the heat. Either serial is dropping because its too fast or its not fast enough to keep the buffer full.

**Comment by andrivet** [comment]
I plan to implement the 1st (baudrate). But for the second, I am not sure.

**Comment by andrivet** [comment]
USB baudrate selection implemented in version 3.0.0.
