### ISSUE TITLE
[FR] Moving E steps without heating up extruder.

### ISSUE THREAD

**Issue by alexten9** [andrivet/ADVi3pp#66]
Sorry was not sure if this is already possible. If so please let me know how.

Im trying to calibrate E steps and I have the motor removed from the nozzel. The motor wont move unless I preheat the nozzel to c180. Is there a way to calibrate it by bypassing the nozzel?

**Comment by jamesarm97** [comment]
Sending the following (via USB serial, repetier host, octoprint or other terminal means) may work. It is a standard marlin gcode. P1 disables the check.

M302 P1      ; disable cold extrusion checking

**Comment by andrivet** [comment]
@alexten9 This is not a feature request. Please do not use issues for support questions.

**Comment by alexten9** [comment]
This was more of a feature request. Just was not sure if it was possible.

**Comment by alexten9** [comment]
It woupd be nice if it coupd be done on the printer it self. Call it cold e step calibration.
