### ISSUE TITLE
Wrong SD card file selection

### ISSUE THREAD

**Issue by chschmit** [andrivet/ADVi3pp#70]
I'm unable to select the file I want from the list of files to print. It appears I need to select the file above the one I want to print. This means I'm unable to select the file that's listed first.

**Comment by f0lie** [comment]
I am having the same issue. I tap on the first one on the list and for some reason, it goes with the one below it. Even with only one file on the entire SD card, I still can't select the first gcode!

**Comment by Jojo-Madman** [comment]
If you only have one file on the card, when touched it highlights but does nothing and does not start.

**Comment by andrivet** [comment]
Fixed in Beta 2
