### ISSUE TITLE
Z height Indicator with 2 decimals

### ISSUE THREAD

**Issue by chschmit** [andrivet/ADVi3pp#71]
Thank you for adding the Z-height indicator.

Are you able to make it read out 2 digits after the decimal?  >  example: 2.15
I print at variable heights that are seldom in multiples of 0.1.

While printing today at 0.15mm heights the read out was showing 0.1, 0.3, 0.4, 0.6...it was just truncating the 5 off the end of some of the readings.

**Comment by andrivet** [comment]
Implemented in Beta 2
