### ISSUE TITLE
Back does not exit Extruder Screen when heating started

### ISSUE THREAD

**Issue by argus357** [andrivet/ADVi3pp#74]
### Bug Report
- Description: If you try to exit extruder screen once heating has started the first press of back arrow begins cooldown setting temp to 0 but does not exit the screen and return to previous menu page. Subsequent presses of back arrow have no effect.
- Expected behaviour: exit extruder screen
- Actual behaviour: remains on extruder screen only way to exit is to press reset
- Steps to reproduce:
  - press back arrow while heating on extruder screen

**Comment by andrivet** [comment]
Temporary fix in Beta 2. Canceling will be implemented in a later release.
