### ISSUE TITLE
Troubleshooting screen

### ISSUE THREAD

**Issue by argus357** [andrivet/ADVi3pp#75]
### Feature Request
Trouble shooting screen to show ‘live’ on/off condition of limit switches, heaters, fans etc on a single page.

**Comment by andrivet** [comment]
It may look like this:

![diagnosis](https://user-images.githubusercontent.com/981049/42287056-2ea8b298-7fb5-11e8-82b7-a24bfbe87b9d.png)

**Comment by argus357** [comment]
Looks good, thank you!

**Comment by andrivet** [comment]
Implemented in version 4.0
