### ISSUE TITLE
Auto PID graph doesn't update

### ISSUE THREAD

**Issue by f0lie** [andrivet/ADVi3pp#78]
### Bug Report
- Description: The graph on PID tuning stays as two flat lines even as the temperature rises.
- Expected behaviour: The graph on the PID change as the hotend heats up.
- Actual behaviour: Starts as two flat lines and remains like that.
- Steps to reproduce:
  - Open PID tuning.
  - Look at the graph not changing.

The top left number changes to the hotend's temperature. I checked by touching it...

It does end up with a value so it looks like just a front end issue.

**Comment by Jojo-Madman** [comment]
Same experience as well myself

**Comment by andrivet** [comment]
Fixed in Beta 2
