### ISSUE TITLE
[FR] Make changing filaments during a print easier.

### ISSUE THREAD

**Issue by brookpatten** [andrivet/ADVi3pp#8]
I'd really like to see the ability to pause a print and swap filaments and have it return to where it was in the print to resume.  If it could cover both the "print from sd" and the "print from pc/octoprint" scenarios then all the better.  It could be implemented as a more general function of just "remember this x/y/z" "return to remembered x/y/z" as well.

**Comment by andrivet** [comment]
Do you mean: implementing a working M600 gcode? Yes, it would be great!

**Comment by brookpatten** [comment]
It sounds like that would do it yes.  Sorry I'm not familiar with much gcode.

Even it was just a UI button where I could pause, move, unload, load, "return", and resume that would do the trick too for a lot of cases.  I think having m600 where you could plan a change is great too, but I was thinking more along the lines of "oh shoot I'm almost out of filament" type scenarios where the gcode is already running and you want to do it from the UI.

**Comment by Burritobun** [comment]
Looks like the M600 code really would need an LCD to let you know what steps you have to take next. Getting the LCD to show M117 codes would be the first thing to sort out.

**Comment by chschmit** [comment]
The Wanhao3 firmware allows pausing the printer to make a filament changing during printing. When you press the UI pause button, the head immediately moves to front of the print bed and the filament can then be manually inserted (auto filament loading doesn't work). After you've 'primed' the nozzle with the new filament, pressing the UI play button will resume the print job. I've made many flawless prints this way, especially when I'm trying to use up short pieces of filament.
This is one of the few features I like about the Wanhao3 firmware, that the alternate ones seem to miss.

**Comment by Scottm80** [comment]
I am also having issues with this.

I use Octoprint and S3d. I want to colour swap on prints but I can't. The machine seems to loose home position. 
I have tried using multiple processes in S3d and the new multi color plugin with Octoprint. Both methods will not work because the firmware looses the home position. So frustrating.

**Comment by Mobsbobs** [comment]
This process for colour change does work in S3D. you create multiple processes and in "Prepare To Print" you save each process as a seperate print job. I have done many multi colour prints this way.

**Comment by sniperxnl** [comment]
M600 code is the best way to use what i have tested last year, thats why i
asked

**Comment by sniperxnl** [comment]
@Mobsbobs can you show me how?

**Comment by andrivet** [comment]
Implemented in Beta 3
