### ISSUE TITLE
Pin Outs for BL touch

### ISSUE THREAD

**Issue by Bigfellas** [andrivet/ADVi3pp#80]
Not an issue. Just wondering if you could post a photo of the pin outs for the BLtouch

**Comment by andrivet** [comment]
Already published for Patreon sponsors. Other users will have to wait a little. I am closing this since it is not an issue or a feature request.

**Comment by Bigfellas** [comment]
Great Please send me a link to your Patreon

**Comment by andrivet** [comment]
www.patreon.com/andrivet
