### ISSUE TITLE
Multiple PID tune memory, or auto PID tune.

### ISSUE THREAD

**Issue by Mooncabbage** [andrivet/ADVi3pp#81]
Would it be possible to add a feature whereby the firmware stores multiple PID profiles for different hot end temps, or they are generated on an as-needed basis? I find myself printing at different temps, even with the same filament, depending on what I want to achieve, or as I tweak my settings. Having the wrong PID tune seems to cause some fairly awful artifacts. It would be nice if the firmware could be a bit smarter about how to achieve/maintain a given temperature, rather than have to run the PID tune every time I want to change the hot end print temp.

**Comment by lightseeker34** [comment]
This would be good feature to have. My new printers have this feature. It's becoming standard. During the pause, a Z+ movement would help keep the print clean.

**Comment by andrivet** [comment]
It looks like this:

![pidsettings](https://user-images.githubusercontent.com/981049/47660118-a4b98880-db96-11e8-9986-e39eb7a3f261.png)
![pidtuning1](https://user-images.githubusercontent.com/981049/47660131-ab480000-db96-11e8-8b90-622cb627d5e8.png)

5 PID values are kept (5 for hotend and 5 for bed). When a target temperature is selected, the most close PID settings are selected.

**Comment by andrivet** [comment]
Also related to #101 and #39

**Comment by andrivet** [comment]
Implemented in Alpha 1
