### ISSUE TITLE
Frozen printer after ABL

### ISSUE THREAD

**Issue by john-f-chamberlain** [andrivet/ADVi3pp#83]
### Bug Report
- Description: The printer can become unresponsive if the "Back" button is pressed after ABL is complete.
- Expected behaviour: When pressing the "Back" button on the ABL complete screen it should repeat the ABL process.
- Actual behaviour: It displays "In Progress" in the corner and does nothing. A force reboot of the printer is required to regain control.
- Steps to reproduce:
  - Go to Tuning > Sensor > Leveling
  - Wait for the process to complete and for the "bed" with readings to display
  - Press "Back"

**Comment by andrivet** [comment]
Fixed in Beta 2
