### ISSUE TITLE
SD Card (Print menu): Directories are displayed like if they were files

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#84]
If you have directories on your SD card, there are displayed in the SD Card screen.

**Comment by chschmit** [comment]
Is this planned for Beta 2? Also, isn't this a duplicate of #21

**Comment by andrivet** [comment]
No, it is not a duplicate. And no, it is not planned for Beta 2.

**Comment by andrivet** [comment]
Directories are now displayed as: [Directory Name]
If you select a directory, it is ignored.
