### ISSUE TITLE
Z Home moves to center of bed

### ISSUE THREAD

**Issue by mikochu** [andrivet/ADVi3pp#85]
### Bug Report
- Description: Z Home is incorrectly moving the extruder to the center of the bed.
- Expected behaviour: In 2.1.0, homing sent the extrude to X0 Y0 Z0.
- Actual behaviour: When sending G28 Z0, extruder moves to X100 Y100 Z0.  When homing to XYZ, extruder goes to X0 Y0 then moves to X100 Y100 Z0.
- Steps to reproduce:
  - Flash 3.0.0 Beta 1 LCD firmware via img file on MicroSD.
  - Flash 3.0.0 Beta 1 firmware via OctoPrint advdude/firmware updater
  - Send homing commands.

**Comment by andrivet** [comment]
This was done on purpose (not a bug). However, as it confuses people, I change it back in Beta 2

**Comment by mikochu** [comment]
@andrivet I just saw.  Sorry for submitting a duplicate of https://github.com/andrivet/ADVi3pp-Marlin/issues/77

If it is by design, I assume we have to change our starting gcode to avoid issues?

**Comment by andrivet** [comment]
As I said, this is fixed by Beta 2 (released in a few minutes)
