### ISSUE TITLE
Cant change thermistor type

### ISSUE THREAD

**Issue by alokbhargava52** [andrivet/ADVi3pp#86]
Thank you for submitting your feedback to the ADVi3++ project.
Please use one of the templates below to fill out this box.

------------------------------------------------------------
### Feature Request
Please put [FR] in the issue title: `[FR] Add-on that goes 'ping'`

------------------------------------------------------------
### Bug Report
- Description: --- 

Can't change Thermistor type to 5 as needed to implement E3D extruder
- Expected behaviour: ---

It should be possible to easily change

- Actual behaviour: ---
- Steps to reproduce:
  - Open the configuration.h file
  - Change thermistor type to 5
  - Recompile
  - You see an error saying thermistortable_5.h missing 
  

------------------------------------------------------------
### Bug Report Tips
- Format text with: **bold**, _italic_, `code`.
- Format C++ with three backticks, plus "cpp":
```cpp
void my_function(bool do_it) {
  // Hold this spot
}
```

**Comment by andrivet** [comment]
There is no bug here. If you need to change the thermistor type, get the thermistortable_5.h from Marlin.

**Comment by alokbhargava52** [comment]
Thanks. 

I had no idea that I had to add missing files from the original marlin 1.1.8. I did it and able to compile successfully. 

One question: I installed your hex files and also flashed lcd and it got installed successfully. On testing I found extruder motor doesn’t turn. I had done boden configuration with e3d heat block. 

Motor is ok. I think motor driver got burned. What must have caused it? I’m very careful person and go step by step. Ribbon cable is ok. 

Thanks,
Alok

**Comment by alokbhargava52** [comment]
I have ordered the new 5.4 mother board but is there a way to repair the old one? Drivers are fixed and not replaceable. 

Alok

**Comment by andrivet** [comment]
@alokbhargava52 1) No idea. 2) 5.4 motherboard? Are you sure it will be compatible with your printer. Do you have a link to this motherboard (where you ordered)?

**Comment by alokbhargava52** [comment]
https://www.reprap.me/wanhao-main-board-to-duplicator-i3-plus-v5-4.html

**Comment by andrivet** [comment]
I think that this is for Mark II (the new i3 Plus). And it is NOT compatible this i3 Plus version 1. Look at the connector for the flat cable: there are 2x10 pins instead of 2x8. You need version 5.1

**Comment by alokbhargava52** [comment]
Oh. Thanks for alerting me. 

Alok

**Comment by andrivet** [comment]
You probably need this: https://www.reprap.me/wanhao-main-board-to-duplicator-i3-plus.html


On Apr 9, 2018, at 22:50, alokbhargava52 <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh. Thanks for alerting me.

Alok

**Comment by alokbhargava52** [comment]
Thanks, you are very helpful.

Thanks,

Alok Bhargava
925-963-2565 (M)

**Comment by alokbhargava52** [comment]
Some more info for you for i3 plus mark2. 

Alok

Sent from my iPhone 8 plus, iOS 11.3

Begin forwarded message:

> From: merry <merry@wanhao3dprinter.com>
> Date: April 10, 2018 at 10:15:44 PM PDT
> To: "Alok Bhargava" <alokbhargava@gmail.com>
> Cc: sales <sales@wanhao3dprinter.com>
> Subject: Re: Re: V5.4 for I3 plus
> Reply-To: merry <merry@wanhao3dprinter.com>
> 
> Dear Alok,
>  
> Pls check below difference for the I3 PLUS motherboard.
>  
> V5.1 is for  i3plus
> V5.4 is for  i3plus Mark2
>  
>   
>  
> Sincerely,
>  
>  
>  
> Merry
> Oversea Sales Dept Manager
>  
> 
> What a Difference Hard Work Makes!
> 
> HANGZHOU WEIBIN TECHNOLOGY CO.,LTD
> 
>  
> NO.198 GAOKE ROAD, FUYANG, HANGZHOU,ZHEJIANG, CHINA, 311400
> 
> WEB: WWW.WANHAO3DPRINTER.com
> 
> MOBIL: +86-15067941363
> 
> SKYPE: wanao-service-01
>  
> EMAIL: merry@wanhao3dprinter.com
>  
> 
> 
> 
> 
> 
>  
> From: Alok Bhargava
> Date: 2018-04-11 05:22
> To: Merry
> Subject: Re: V5.4 for I3 plus
> You may look at the following link:
> 
> https://www.reprap.me/wanhao-main-board-to-duplicator-i3-plus-v5-4.html
> 
> 
> Thanks,
> 
> Alok Bhargava
> 925-963-2565 (M)
> 
> 
> 
> 
>
