### ISSUE TITLE
Load filament screen: Numbers show over each other

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#91]
https://www.facebook.com/photo.php?fbid=10101399947895301&set=p.10101399947895301&type=3

**Comment by andrivet** [comment]
Duplicate of #8 and #18

**Comment by wescrockett** [comment]
Sorry I didn't open it here. I meant too, but I was a tad too lazy and was on my phone.

The unload screen does not have the issue. Here are my screen shots:
https://photos.app.goo.gl/4Od0yhdgb0CqqxH03
https://photos.app.goo.gl/hJjghHGXiqcTNAXq2
https://photos.app.goo.gl/qNywlcAMnoMRk4vf1

**Comment by andrivet** [comment]
Fixed in Beta 3
