### ISSUE TITLE
BUG: Beta 2 - Homing X sometimes does not work.

### ISSUE THREAD

**Issue by wescrockett** [andrivet/ADVi3pp#92]
When working with Beta 2, I have found that, at times, the X axis will not home... whether through octoprint or the printer control display.

It seems to happen when you have manually moved the head at some point when it previously thought it was already homed.

I will try to iron out the reproduction steps, but it seems to think it is already homed.

**Comment by andrivet** [comment]
Duplicate of #15

**Comment by wescrockett** [comment]
Ah. sorry. thanks!
