### ISSUE TITLE
Loading/Unloading Extruder Keeps going after exit

### ISSUE THREAD

**Issue by Jojo-Madman** [andrivet/ADVi3pp#97]
### Bug Report
- Description:
When loading or unloading filament into the extruder, once accomplished and user exits, the extruder motor continues to run (unload or load direction) for approximately 20 seconds more.

- Expected behaviour:
In past versions, extruder motor stopped immediately upon exiting, which wasted less filament and made less mess at the nozzle.

**Comment by Jojo-Madman** [comment]
Also, while extruder motor is still loading/unloading after exit, the menu navigation still works, but issuing a command such as to start a Print will not accept or to home all, and extruder has to come to stop before another command will work.

**Comment by andrivet** [comment]
This bug is apparently due to a race condition. G90 is called sometimes too early and thus G1 E1 is no more relative and do strange things.

**Comment by andrivet** [comment]
Fixed in Beta 3
